### ISSUE TITLE
BOM Pricing For One Part Not Carrying Over

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree#1045]
I have a BOM that has one sub-part that shows Qty of 2 and Available 29 with cost of "Not available". The part previously had pricing breakdown but I had not selected the currency. I edited the two pricing levels by adding "USD" as the currency but the BOM still shows "No Pricing Available" after calling up the BOM anew. How do I fix this?
--Larry

**Comment by eeintech** [comment]
@LarryJoy Please provide some relevant screenshots
* Build details
* Part BoM tab
* Supplier Part price breakdown for the sub-part

**Comment by LarryJoy** [comment]
I did not try to build this part (assembly). Here is the Supplier Part price breakdown for the one particular sub-part:
![image](https://user-images.githubusercontent.com/18520951/96029485-bf8b7300-0e28-11eb-905f-e8fe90781cdf.png)
And here is the BOM showing the part:
![image](https://user-images.githubusercontent.com/18520951/96029824-2b6ddb80-0e29-11eb-87d4-ec68e9944ed7.png)
The sub-part (item) in question is the 2nd line with Reference (ref des) of 1H1.
--Larry

**Comment by eeintech** [comment]
After some digging, it turns out the current logic fetches the price breakdown where quantity in the BOM is superior to price break
In your case:
- the lowest price break is for quantity = 4 ($0.26)
- in the BOM, the quantity of `1H1` part is 2

:arrow_right:  There isn't any price breakdown lower or equal to 2 in the supplier part (minimum is 4), therefore the `No pricing available` message

The current implementation ignores higher price break groups and while I don't think it is optimal, it would take multiple assumptions to include those (eg. overstocking/overbuying).

The easiest workaround now is to add price breakdown at unit level (quantity = 1).
