### ISSUE TITLE
CSV import

### ISSUE THREAD

**Issue by jacobwilson2** [inventree/InvenTree#1069]
Hello,

I am attempting to use InvenTree for my business's inventory system. I am currently just using excel sheets. Is it possible to import my excel sheets to Inventree. Thanks you for your time!

**Comment by eeintech** [comment]
Hello @jacobwilson2 

This is not documented yet but yes it is possible to import data using CSV, XLS or XLSX formats (or even JSON and YAML formats). The catch is that all items (parts, stock items, purchase and sales orders, etc.) will have to imported separately into InvenTree, from different spreadsheets (as columns matching are different depending on the type of object you wish to import).

What do you wish to import? Can you share a sample of non-confidential data?

**Comment by jacobwilson2** [comment]
Hello,

I messaged you on Friday regarding adapting InvenTree to be used for my small business. We are a small e-commerce company that redistributes tech products. I have a sample of our books that I can share with you if you would like to see. Thanks so much for your time. You can reach me at jacob.techable@gmail.com

**Comment by eeintech** [comment]
@jacobwilson2 I'm sorry but I did not get any email from you.

Do you mind to attach this sample file of books you mentioned here? If we can help you import, this would also help other users understand the process.

**Comment by jacobwilson2** [comment]
Awesome, thanks so much. I've attached a sample of what our books. 

[dummySheets (1).xlsx](https://github.com/inventree/InvenTree/files/5445893/dummySheets.1.xlsx)

**Comment by eeintech** [comment]
@jacobwilson2 I've looked over the spreasheet quickly and it is going difficult to import as-is, you may have to split it in multiple sheets.

Basically, to import your list into InvenTree, you'll need to match your columns to InvenTree fields.

With InvenTree running locally, navigate to: http://127.0.0.1:8000/admin/part/part/import/

There you will see the following message:
```
This importer will import the following fields: category, default_location, default_supplier, category_name,
variant_of, suppliers, in_stock, on_order, used_in, allocated, building, id, name, is_template, description, 
keywords, IPN, revision, link, image, minimum_stock, units, assembly, component, trackable, 
purchaseable, salable, active, virtual, notes, creation_date, creation_user, responsible
```

In your spreadsheet, you'll need to match (in other words: rename) the XLSX columns to those fields, for instance:

| XLSX column header | InvenTree field |
| --- | --- |
| Item# | IPN |
| Seller | default_supplier |
| Type | category |
| ??? | name |

> Note that the `name` field is required, you don't seem to have any direct match.

You'll also need to create categories before hand: MacBook Pro, MacBook Air, etc.
So that your items can imported in each category.

Once you are done with the matching, click on "Choose File" and select your spreadsheet.
Select `xlsx` as the format and then click on "SUBMIT" button.

I'm sorry it's a lot of scrambling around, please experiment on your side and if you encounter any problem contact us so we can try to resolve it.

**Comment by eeintech** [comment]
Hello @jacobwilson2 Did what I mention make any sense?

**Comment by eeintech** [comment]
@jacobwilson2 Following-up in this, any update from your side?

**Comment by SchrodingersGat** [comment]
Hi @jacobwilson2 as this has gone quiet for a while I'm closing out this issue. Please note that I have recently updated the docs for importing data:

https://inventree.readthedocs.io/en/latest/admin/import/
