### ISSUE TITLE
Load onto 'non GUI' server

### ISSUE THREAD

**Issue by watarat** [inventree/InvenTree#1089]
I'm pretty much "following the bouncing ball" here, (So i'm not digging too far into the code with my limited skills) but my incremental approach to getting a web server implementation has stalled.  
Prior to trying to get a cloud based solution - I've tried to install onto just a local Ubuntu Server within a VirtualBox VM.  
Mainly to prove it works there, before getting sidetracked on other server issues.  
The install procedure work fine (as per the install guide) until I try and run "invoke superuser" - where it fails over installation of Cairo, which seems to be graphical user display  module - not relevant for the Server install ?? I think I managed to get Cairo sorted (maybe not completely) but now have an issue with 'Pango' which seems a bit more intractable!!
Server also fails to run over same issue.  
Is there something I'm missing, or do I actually need a full GUI server instance ??

**Comment by SchrodingersGat** [comment]
Hey @watarat welcome :)

It looks like what is happening here is you're getting stuck at the install requirements for [weasyprint](https://weasyprint.readthedocs.io/en/stable/install.html). This is a python package used for PDF generation, which is why it requires graphics packages to be installed.

"Normally" those packages would be installed on a ubuntu-ish setup (I think?)

Follow the [Linux Setup Instructions](https://weasyprint.readthedocs.io/en/stable/install.html#linux) for weasyprint to ensure those other packages are installed.

I'll have to add this into the install script to check for these packages

**Comment by watarat** [comment]
Ahh - fantastic - worked well 😀
Ran through all of the packages listed in your link
`sudo apt-get install build-essential python3-dev python3-pip python3-setuptools python3-wheel python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info`
Several installed..
Re running `invoke install`, then `invoke superuser` succeeded, and is now running server.
Many thanks!!
(I had read of Cairo being used in weasyprint - but hadnt made the connection that all of weasyprint was needed for the pdf, just assumed that Cairo was part of some GUI output :) )

**Comment by SchrodingersGat** [comment]
Thanks for the feedback - glad it is working for you now!

I'll make a note to update the install documentation to include these requirements
