### ISSUE TITLE
Components cannot be added to more than one BOM

### ISSUE THREAD

**Issue by wolffam** [inventree/InvenTree#1160]
Similar or same issue as #1141 where intermittently components cannot be added to more than one BOM.  I tested the fix in #1141 and it seemed to work (I refreshed a couple of times to check).  However, we have started to detail BOMs for other parts in our system and it appears the bug has reared its head again.

So far, we haven't been able to find a common thread or link between issues but we are sandboxing again to try and find a repro.  Seems like it might happen now more often when adding to the 3rd BOM

**Comment by SchrodingersGat** [comment]
If you can provide an example dataset where you can reliably reproduce this issue, that would be great.. Last time around was difficult to replicate and "fix" (although maybe it wasn't even a complete fix).

**Comment by wolffam** [comment]
This is the simplest repro I can show.  Not sure why the last time I hit this, it appeared to test out successfully.
![Screen Shot 2020-12-17 at 1 21 11 PM](https://user-images.githubusercontent.com/11801197/102545161-bdcd6e00-406a-11eb-98de-8739a959c46a.png)

![Screen Shot 2020-12-17 at 1 19 47 PM](https://user-images.githubusercontent.com/11801197/102545070-9b3b5500-406a-11eb-8f3d-f92603b2469c.png)
![Screen Shot 2020-12-17 at 1 18 50 PM](https://user-images.githubusercontent.com/11801197/102545083-9c6c8200-406a-11eb-9881-c10a002d10ec.png)
![Screen Shot 2020-12-17 at 1 18 23 PM](https://user-images.githubusercontent.com/11801197/102545086-9d9daf00-406a-11eb-8d2f-15e05b640122.png)
![Screen Shot 2020-12-17 at 1 17 45 PM](https://user-images.githubusercontent.com/11801197/102545092-9e364580-406a-11eb-80f2-abf383535aea.png)

**Comment by neco1982** [comment]
I had the same problem i stopped the server and restarted components loaded

**Comment by SchrodingersGat** [comment]
Ok, this one is *very strange*...

I have narrowed it down to *where* the issue is, but have no idea why...

The issue is occurring in `part/models.py` in the function `getRequiredParts`. The function itself is correct, but returns incorrect results depending on how it is called.

I followed your steps above to reproduce. In the images below, the component is added to the BOM of Assembly 2, and I am trying to add it to the BOM of Assembly 1:

## Cannot Find the Component 
![image](https://user-images.githubusercontent.com/10080325/103467985-c9c66900-4da8-11eb-9430-c9c2aa3d7566.png)

## Instrumenting Code

I added some simple debug statements to see what was going on.

![image](https://user-images.githubusercontent.com/10080325/103467995-ec588200-4da8-11eb-9c67-a03764fd3142.png)

## Server Logs

The server indicates that getRequiredParts is returning a non-empty queryset (which is incorrect).

![image](https://user-images.githubusercontent.com/10080325/103468005-02fed900-4da9-11eb-948e-bf9a73f5137d.png)

## Run Code Manually

Run the same code from localhost:8000/admin/shell

![image](https://user-images.githubusercontent.com/10080325/103468021-2e81c380-4da9-11eb-8b79-a1d2b53ba1b3.png)

Once again, this code returns an incorrect result.

## Run Code from External Shell

If you run the same code from the command line, the function returns the correct result:

![image](https://user-images.githubusercontent.com/10080325/103468040-596c1780-4da9-11eb-976c-b9ecffd1259b.png)

## Restart Server

If the server is restarted, then the function returns the correct result also.


================================

So, it appears that there is some sort of server cache issue here?

**Comment by SchrodingersGat** [comment]
Ah. Oh. Ok.

So it was as simple as variable scoping. Fix incoming.

**Comment by eeintech** [comment]
@SchrodingersGat Tough one, well done!
