### ISSUE TITLE
config.yaml not found

### ISSUE THREAD

**Issue by neco1982** [inventree/InvenTree#1181]
Hello I just cloned the source codes. I create venv installed requirements.txt. When i tried to makemigrations or any other runserver.py command getting error Error: config.yaml not found. Would you please help me? Thank in advance. Best Regards.

**Comment by SchrodingersGat** [comment]
Hi @neco1982 did you close this issue because you got it working? If you have not solved it yet, please leave the issue open until it is resolved.

As per the docs, you should run the command `inv install` - https://inventree.readthedocs.io/en/latest/start/install/#installation

This will create a config.yaml file (if it does not exist) and perform other necessary steps. You should not have to manually perform individual installation steps.
