### ISSUE TITLE
Supplier_Part import failure (Part instance does not exist)

### ISSUE THREAD

**Issue by dtcomp** [inventree/InvenTree#1188]
I imported parts from my spreadsheet then,
It seems Supplier_Parts are required to add my stock.
I generated a CSV with supplier parts to import, resulting in the same error message for each line:
"Part instance with id {X} does not exist"
Where: {X} = id of the Part instance.
But, indeed, the part instance does exist in my database..
Perhaps not a bug but something i am missing? 
(I installed from git just a few days ago)

Aside: I am unfamiliar with the way the code is packaged and laid out -
Some simple attempts to locate actual import code has yielded only html and templatting
stuff.

Any hints as to where I should be looking?

**Comment by dtcomp** [comment]
My issue may not be relevant -
It appears I don't really require "Supplier_Parts" and I was able to import initial stock quantities via admin interface.

**Comment by SchrodingersGat** [comment]
@dtcomp I think I understand what has happened here.. I tried (and eventually succeeded) to replicate the issue you were seeing.

The message `Part instance with id <X> does not exist` is probably because the referenced Part object was not marked as 'purchaseable'.

The data import process uses the [django-import-export](https://django-import-export.readthedocs.io/en/latest/) library which does not always produce very helpful error messages.
