### ISSUE TITLE
Loading on server

### ISSUE THREAD

**Issue by neco1982** [inventree/InvenTree#1210]
Hi
I tryed to load the app with gunicorn and heroku like usual webpage. I didnt get any error during load everything was good but after loading when i tried to open on browser i got error. In this way i loaded a lot of webpage created on django without problem and they are working well. But Inventree doesnt work. Would you please tell if this loading is not true for multıple users usage. Or do you have any video for server installation.
Thanks in advance

**Comment by eeintech** [comment]
@neco1982 If you're familiar with Django, can you take a look into your server logs to point us to the actual error? Or at least a screenshot of the error you are seeing when navigating to InvenTree?

**Comment by neco1982** [comment]
2021-01-07T17:58:38.624709+00:00 heroku[web.1]: Process running mem=641M(124.6%)
2021-01-07T17:58:38.628709+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2021-01-07T17:58:39.751450+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2021-01-07T17:58:39.777398+00:00 heroku[web.1]: Stopping process with SIGKILL
2021-01-07T17:58:40.497092+00:00 heroku[web.1]: Process exited with status 137
2021-01-07T17:58:40.537317+00:00 heroku[web.1]: State changed from starting to crashed
2021-01-07T17:58:41.320588+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=bayastock.herokuapp.com request_id=8f9e3dc1-d57e-4d44-b284-afa0788df4a5 fwd="88.242.68.71" dyno= connect= service= status=503 bytes= protocol=https
2021-01-07T17:58:41.728063+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=bayastock.herokuapp.com request_id=9c289f9d-7d64-4d3e-816b-9a1f0d2fb17e fwd="88.242.68.71" dyno= connect= service= status=503 bytes= protocol=https
2021-01-07T17:58:43.372621+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=bayastock.herokuapp.com request_id=0399bd2d-d21e-4bbd-a83e-d7025f2992d3 fwd="88.242.68.71" dyno= connect= service= status=503 byt

**Comment by neco1982** [comment]
![image](https://user-images.githubusercontent.com/31635566/103933859-12797b80-5135-11eb-9965-2a4c25b8f272.png)

**Comment by neco1982** [comment]
![image](https://user-images.githubusercontent.com/31635566/103942574-ac472580-5141-11eb-985f-24e439d1824a.png)

**Comment by SchrodingersGat** [comment]
Looks like heroku is running out of RAM? 

![image](https://user-images.githubusercontent.com/10080325/103945927-09ff6000-518a-11eb-87a3-9ebac19ae54d.png)

I do not think this looks like InvenTree's fault

**Comment by neco1982** [comment]
When i start to program on local computer with python manage.py it is working without problem but when i start with command heroku local or unicorn InvenTree.wsgi getting error no module named ‘fcntl’ what can be solution

**Comment by SchrodingersGat** [comment]
Looks like a problem running heroku on windows - I have zero familiarity with this, I'm afraid I can't be of much assistance.

**Comment by neco1982** [comment]
Would you please make a video about installation for multiuser usage? I tried several ways but failed. How to installation on localnetwork and how to get daily backup from server?
Thanks in advance

**Comment by eeintech** [comment]
@neco1982 A multi-user setup is really not that different than a unique user setup, but instead of running locally on your machine, InvenTree would run on a machine accessible on a local network so that anybody connected to that network can access it.

The other important part is to pick a web server application to run InvenTree (instead of the default Django server, which is meant to be used only for testing), I personally use Phusion Passenger. If you're interested I can share my setup and configuration with you. You gonna have to start by installing Passenger on the machine that will host InvenTree: https://www.phusionpassenger.com/library/walkthroughs/deploy/python/

I am not familiar with Heroku and Gunicorn unfortunately, so you'll have to get help from other communities. Look-up for Django applications running on/with those, there must be information out there.

Regarding the database backup, it will depend which you pick: SQLite3, MySQL and PostGreSQL are the main ones.
Backing up a SQLite3 database is as simple as backing up a file, because the entire database content is saved in a single file. I have a good amount of experience with PostGreSQL (and the backup part) so if you pick that one, I could help you setting this up too :)

**Comment by neco1982** [comment]
Thank you for your quick reply. I am not familiar with phusionpassenger i checked some source on internet but i couldnt find enough. Would you please share your setup and configuration with me? Also I will be glad if you can help me about PostGreSQL and backup.

**Comment by eeintech** [comment]
@neco1982 Sorry just realized you responded, did you solve your installation problem? I saw you were running InvenTree in #1216

**Comment by neco1982** [comment]
Solved

**Comment by eeintech** [comment]
@neco1982 Can you explain a bit the solution? In the case another user stumbles upon this issue.
Also maybe worth documenting.

**Comment by neco1982** [comment]
I used digitalocean document to load project and i made all settings like
inventree deploying document.
https://www.digitalocean.com/community/tutorials/initial-server-setup-with-ubuntu-16-04

Here is all necessary documents for uploading. For static file path I used
the path as attached print screen

Francois <notifications@github.com>, 13 Oca 2021 Çar, 01:26 tarihinde şunu
yazdı:
