### ISSUE TITLE
Add "responsible user" for BuildOrder

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1230]
Specify who is responsible for a build order

e.g. for assigning to a particular technician

**Comment by eeintech** [comment]
Would you be inclined to use the [`Owner` model](https://github.com/inventree/InvenTree/pull/1155/files#diff-c7d04953a3ead03a0a663c89a5af315c500ea4ef03fd4b4cee337edfe991f5d8R400) instead of a "User" model? So that the "responsible user" can also be a group, if you have more than one technician or people involved in the build.

Would the "responsible user" be the only one to update the state of the build?

**Comment by SchrodingersGat** [comment]
> Would you be inclined to use the Owner model instead of a User model? So that the "responsible user" can also be a group, if you have more than one technician or people involved in the build.

That's a very sensible idea.

> Would the "responsible user" be the only one to be able to update the state of the build?

Not sure. I think to start it would just be denoting who is "in charge" of the build order. For example we have a number of technicians and I wish to be able to allocate builds to particular techs
