### ISSUE TITLE
Mass BOM items delete does not work

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#1358]
![image](https://user-images.githubusercontent.com/4020546/109076928-629ea400-76c9-11eb-9e47-590e765974fe.png)

**Comment by SchrodingersGat** [comment]
Works on my end (latest master).

- Can you elaborate on "does not work"?
- Do you see any error messages in the javascript console?

**Comment by eeintech** [comment]
I think it is a permission issue:

![image](https://user-images.githubusercontent.com/4020546/109088529-92f03d80-76dd-11eb-87f3-e4b2ddc5700f.png)

Sorry I should dug up more details, I was just to tied up and wanted to remember it.

I believe if the user don't have Parts `delete` permission BOM items wouldn't be deleted.
Obviously we don't want anybody to be able to delete a part but BOM items should be manipulated with `change` permission.

**Comment by eeintech** [comment]
@SchrodingersGat The method for BomItem mass delete is in those two code snippets:

**part/template/part/bom.html**
``` js
                        var row = rows[idx];

                        var url = `/api/bom/${row.pk}/`;

                        inventreeDelete(
                            url,
                            {
                                complete: function(xhr, status) {
                                    deleteRow(idx + 1);
                                }
                            }
                        )
```

**InvenTree/script/api.js**
``` js
function inventreeDelete(url, options={}) {
    /*
     * Delete a record
     */

    options = options || {};

    options.method = 'DELETE';

    inventreePut(url, {}, options);

}
```

Which I think tries to force-brut delete all items with the API `DELETE` method, bypassing the REST framework?

For the single item delete (which works with the permissions), the action is in:

**templates/js/bom.js**
``` js
        table.on('click', '.bom-delete-button', function() {

            var pk = $(this).attr('pk');
            var url = `/part/bom/${pk}/delete/`;
            
            launchModalForm(
                url,
                {
                    success: function() {
                        reloadBomTable(table);
                    }
                }
            );
        });
```

Which in this case uses the REST framework therefore checking the correct permissions? The url is different `/part/bom/${pk}/delete/`.

I'm a little rusty here and lack more time to investigate but it looks like slightly different implementation, with one looking like it is not aware of permission level (mass delete).

**Comment by SchrodingersGat** [comment]
Good detective work! Both API endpoints will allow deletion, but as you have discovered, one has the wrong permission set associated!

I normally just run with superuser status so don't ever come across permission issues :p

Changing the multi-delete ajax request to use the `/api/bom/<x>/delete/` URL should be sufficient here!

**Comment by eeintech** [comment]
I've tried it but it is still giving error:

![image](https://user-images.githubusercontent.com/4020546/109231581-e1144800-7794-11eb-8af4-e54e86d7d487.png)

**Comment by SchrodingersGat** [comment]
On further read through of the code I do not think the REST API currently observes the "role" permissions at all... I think any authenticated user can perform any action via the API.

So I think that this needs to be addressed more fundamentally across the entire API!

**Comment by eeintech** [comment]
Oh I always thought the user's permissions be relevant for the REST API too... good catch 👍

**Comment by eeintech** [comment]
@SchrodingersGat Unfortunately this is not fixed by #1363 

![image](https://user-images.githubusercontent.com/4020546/109517057-de587200-7a76-11eb-95be-5eaee4a28c15.png)

**Comment by eeintech** [comment]
Ok I see. I just found a workaround actually, as both the `Part` and `Build` roles control `BomItem` permissions:

* Part
https://github.com/inventree/InvenTree/blob/278466e8309cfab45e23bf13ae14072e9d7b4b2a/InvenTree/users/models.py#L63

* Build
https://github.com/inventree/InvenTree/blob/278466e8309cfab45e23bf13ae14072e9d7b4b2a/InvenTree/users/models.py#L87

This is probably not the best way to do it but enabling "delete" permission on build let user delete all the BOM items.

Also I'm still confused why deleting each BOM item **individually** works even with no delete permission on either `Part` or `Build` roles?

**Comment by SchrodingersGat** [comment]
> Also I'm still confused why deleting each BOM item individually works even with no delete permission on either Part or Build roles?

Deleting "individually" uses the web-forms and *not* the API, so the permissions system is different.

**Comment by eeintech** [comment]
@SchrodingersGat Ok makes sense. How are API permissions set compared to web view permission (which I'm already familiar with)?

**Comment by SchrodingersGat** [comment]
Good question. With the recent updates to the API permissions (which were completely absent until recently!) the HTML forms and API endpoints are slowly converging in terms of the way they operate.

## HTML Forms

HTML forms (most modal forms in the InvenTree web app) inherit from the `AjaxMixin` class:

https://github.com/inventree/InvenTree/blob/7f6f48946353109c2b1efd26fa5fe78258eba6ae/InvenTree/InvenTree/views.py#L170

Which in turn inherits from `InvenTreeRoleMixin`

https://github.com/inventree/InvenTree/blob/7f6f48946353109c2b1efd26fa5fe78258eba6ae/InvenTree/InvenTree/views.py#L112

`InvenTreeRoleMixin` allows us to specify a *role* associated with the particular View (such as `stock.view`), rather than the default way that django handles this - by specifying particular permissions (such as `company.view_supplierpart`.

To do this, we add the `role_required` attribute to the View:

https://github.com/inventree/InvenTree/blob/7f6f48946353109c2b1efd26fa5fe78258eba6ae/InvenTree/stock/views.py#L52

## API Endpoints

The API code is based on this, but is a lot *nicer* (based on what I have learned since the HTML form role permission code was implemented).

The class `RolePermission` defines role-based permission behavior for the API endpoints:

https://github.com/inventree/InvenTree/blob/7f6f48946353109c2b1efd26fa5fe78258eba6ae/InvenTree/InvenTree/permissions.py#L9

This permission class is defined as the "default" permission class (in settings.py) and so, unless otherwise specified, every API endpoint uses this permission.

It introspects on the database model associated with the endpoint, and then works out if the user does indeed have the correct permissions to access that *model*. 

This way we don't have to specify roles per API endpoint - it works it out by itself.

Soon I will look at making the HTML forms introspect permissions in the same way - it's much simpler and less to get wrong!
