### ISSUE TITLE
Parameters for suppliers

### ISSUE THREAD

**Issue by TheITStudent** [inventree/InvenTree#1434]
I need to have more parameter than just the price for the supplier, 
Is it possible to commit a modification to have other parameters for the supplier ?

**Comment by SchrodingersGat** [comment]
This would most likely require an additional field in the database, which is entirely possible.

What extra parameters are you looking for?

**Comment by TheITStudent** [comment]
in our company, a Part have many Suppliers, and the Part don't have all the Parameters but the supplier have specifics parameters, as we can have with the Part

**Comment by TheITStudent** [comment]
So for our database to be compatible we need to put parameters into Supplier Part, will it be possible ?

**Comment by eeintech** [comment]
@TheITStudent I'm curious, why would your preference go to having parameters at the supplier part level? It is much more limiting than at the part level because a part can link to multiple supper parts. I don't see the use-case where those multiple supplier part are different from each other and linking to the **same** part. In that case, I would always have a new part for a different supplier part. So parameters would follow the part, not the supplier part.

**Comment by TheITStudent** [comment]
@eeintech  we have one part with many suppliers, they are all equivalents, but they don't have the same origin, SVHC or ROHS for example and i need some parameter into the supplier part to put this.

**Comment by eeintech** [comment]
@TheITStudent So you want a "Compliance" field inside the supplier part? Is that all you need?

**Comment by TheITStudent** [comment]
yes that all i need, it is possible ?

**Comment by TheITStudent** [comment]
I just reread, and it's not just one "Compliance" field but many fiels, like for the Part parameters

**Comment by fjullien** [comment]
> I don't see the use-case where those multiple supplier parts are different from each other and linking to the **same** part. In that case, I would always have a new part for a different supplier part. So parameters would follow the part, not the supplier part.

@eeintech there are cases where multiple supplier parts are compatible but not exactly the same. For example, their temparature range are not the same but they both fit the part expected temperature range. If you want to display this parameter in your BOM then you want to have it in the supplier parameters.

There is a lot of examples like this. That's why arbitrary parameters for suppliers would be great.

**Comment by eeintech** [comment]
@fjullien While I disagree that two supplier part with different spec (like temperature range) should be attached to the same part (instead of creating a different part), I have to admit that more general flexibility is always welcome for new use-cases.

@TheITStudent I am revamping a bit the `SupplierPart` model (but transparent to all users) and adding a new model called `ManufacturerPart` which will contain the manufacturer data (the `SupplierPart` will just be pointing to it). From what I understood, you really would like those parameters connected to the manufacturer, am I assuming right?

**Comment by TheITStudent** [comment]
@eeintech thank you for your modifications, the Parameter don't have to be connected to the manufacturer, but to the supplierPart, to be more precific, the best would be to add parameter part into the supplier part, like the pricing information.
I put a picture to explain where more precisely
![inventree param](https://user-images.githubusercontent.com/81369477/113287504-f75e7800-92ed-11eb-96c2-e19be3fb50a9.png)

**Comment by TheITStudent** [comment]
is it a better explanation ?

**Comment by eeintech** [comment]
@TheITStudent I understood clearly what you're asking. I will show you soon what the `ManufacturerPart` is.
I think it will be a better place to put those, because supplier item is just the distribution of the actual manufactured part (which you would attach different parameters too).

**Comment by eeintech** [comment]
@TheITStudent This is an **early** preview but this is how the new Manufacturer part table will look like (under Part view):

![image](https://user-images.githubusercontent.com/4020546/113306030-a6d92180-92d1-11eb-9ead-2c9264440a2f.png)

This will be the "Manufacturer" detail page:

![image](https://user-images.githubusercontent.com/4020546/113306217-d9831a00-92d1-11eb-9080-b7684b95b2af.png)

Here I'm thinking this will be the right place to put parameters :smiley:

**Comment by TheITStudent** [comment]
I agree, that can be the good place to put the parameters. 
thank you
