### ISSUE TITLE
My thoughts and ideas about InvenTree project.

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#1471]
First, I would like to thank @SchrodingersGat, @eeintech and all other contributors for all you have done.

Some background: I'm an electronics hobbyist and one day (like everyone else) I realized that excel is not enough for me to keep records about my parts and pieces. So, I searched and I found many inventory systems: some of them were too simple or generic, some - too complex or pricy. Others were opensource and electronics-oriented but lacked support and development efforts. Eventually I decided to create my own system using Python + Django (sounds familiar?). 
I  defined the following features to be implemented:
- Tracking of any items not only electronic parts.
- Hierarchical categories
- Any number of tags could be assigned to each item (part). The same tags could be assigned to stock items to differentiate between new and used parts, for example. Tag cloud on part table display.
- Category-specific parameters because it is logical.
- New parts should be created (wherever possible) only via import from supplier’s database. It doesn't make sense to enter all part info manually when we already have pretty good databases of parameters, pictures and datasheets. Import from many suppliers should be supported to select the most useful information.
- Multiple images, links, attachments per part should be supported. Images could also be the links to a supplier’s website.
- Dynamic linking of related parts. If I know for sure that some parts are interchangeable, why bother to manually enter this information?  
- The main view for parts is a table as in excel, with a quick filter by part name and parameters.

The main idea was to create a system that will be as simple as excel to enter new info and display existing parts and at the same time more powerful and extensible. 
I'm a hobbyist after all and I just want to know which parts I have and where they are stored but since we live in the 21-century, computers could be used for more than a spreadsheet.
So, I spent a couple of weeks to code my system and then imported all my parts into it but it still looked like something quickly thrown together.

Some time passed…

And then I came upon **InvenTree**. It looked promising from the first sight: python, django, database, API, mobile app.
I installed it, added some parts, tested other features, created a couple of feature requests and issues on github. 
I came to the conclusion that it is more business (than hobbyist) oriented because it has all this Buy and Sell stuff that I don’t need. Anyway, Purchase Orders could be useful for me too (see further below).
I decided to post here my ideas of how to improve InvenTree and make it more convenient. Maybe some of them will be helpful and deserve development or maybe not. Anyway, I will be glad to describe them in greater detail if needed.

**UI/UX**

- Change main part page template. Move current “Part Details” tab to sidebar. Replace it with part notes + limited list of parameters + limited list of attachments. Display real stock entries instead of “Available Stock” stats. If there are more than N stock items, add link to “Stock” tab. Main idea: why click on tabs if we can get all info on main page.
- Add spaces to category delimiter “ / ”. Currently it is hard to read.
- Display links as icons in Parts or Stock tables. It will save screen space.
- Reformat “/part/” page. Currently half of the page is occupied by nested categories, why not replace this list with selector like in “edit properties”. 
- Remove sidebar animation. It is cool but only wastes time.
- In Parts table, remove full category path in “Category” column to save space. Display only last category and full path in tooltip.
- Change category selector in “Edit properties”. Remove redundant category names in nested categories.
- In “Purchase price” and “Stock Quantity” fields up/down buttons change only the last fractional digit which does not make sense.
- Add “add stock” button to main part page or to “Count Stock Items” dialog.

**Ideas, questions, issues**
- What is the meaning of “Packaging” when adding stock? Is it about storage package (bag, box) or part package (DIP/SOIC)?
- Unified images/links/attachment system #1312.
- Add support for wildcards (*,?) or regexp in tables “search”.
- Add time to "stock_stockitem.updated" and "part_part.creation_date" to have ability to sort items by create  or update time. Add “updated” column to Parts table.
- Add grand total row for “Quantity” and “Unit Price” in Purchase Order Items.
- History of purchase prices for specific part. Take info from PO.

**Purchase orders** 
Let me first describe my current workflow of purchasing new parts. 
- Create PCB design in EDA (Kicad).
- Export BOM with parts values and footprints.
- Check my stock to mark parts that I already have. 
- For each new part search Supplier website database to find a good match. 
- Add all parts to basket, do a checkout and wait for shipping. 
- Add newly arrived parts to my inventory system and put them to designated storage locations.

It does not make sense for me to track exact supplier’s parts as it currently implied in InvenTree. All I need from PO is a track of money spent on specific parts from a specific supplier. If I need to find an exact part number, I could use PDF attached to PO or supplier’s order history.
All BOM / Build orders functionality also depends on supplier’s parts.
So, the idea is to make a lightweight PO processing without a requirement to add supplier’s parts.

I know it is a longread, but I decided to post it all in one issue to keep it whole. Thanks for your attention.
Please feel free to ask any questions or give me any feedback.

**Comment by SchrodingersGat** [comment]
Hey @sintech thanks for your input. Reading through your ideas here, I think a lot of them have a lot of merit. 

However there is *far* too much to deal with on a single issue!

I would suggest you break your ideas down into separate issues, and there we can discuss the merits and implementation of each idea separately. Perhaps you would be willing to contribute towards some of the issues too?

Cheers,
Oliver

**Comment by sintech** [comment]
Thanks for feedback @SchrodingersGat. 
Sure, I will create one issue per idea to be more productive.
I'd love to contribute but my experience with django is pretty limited (only one semi-complete project).
I guess I will try to implement something on my own, do a PR and then we'll see.

**Comment by SchrodingersGat** [comment]
Sounds great! If you get stuck diving into the code I'm more than happy to help.

It's grown into a pretty large project now, so please don't feel overwhelmed :)

**Comment by eeintech** [comment]
@sintech I started exactly as you did, but from a different angle.

One thing that KiCad is **badly** missing is decentralized database of parts. I just couldn't cope (and still can't in some way) with the fact that each resistor (and other common parts) need to have a unique symbol in the library. So much efficiency waste in designing circuits!

Anyhow, my new team needed an inventory system and I needed to find a way to connect KiCad parts to this inventory system. I evaluated some commercial solution, none of them were satisfying. Then bumped into InvenTree.

At first I was lost. I knew Python but nothing of Django, so InvenTree looked foreign. I started doing a silly Django project where I would grab the Octopart API's search data from a part number and create an database instance of that part. It was fun but obviously I couldn't connect it to KiCad because web app cannot manipulate the file system.
With more knowledge on Django, I looked for low-hanging fruits in InvenTree and little-by-little, reading **a lot** of doc and articles, made my way through the InvenTree structure that @SchrodingersGat built, installed few instances on our company's servers and connected InvenTree to KiCad with a custom tool ([Ki-nTree](https://github.com/sparkmicro/Ki-nTree/)).

When a coworker of mine or GitHub user goes about "I wish I could do this in InvenTree" and find it relevant, I add it to my TODO list. Of course Oliver would decide on the usefulness of that feature and proper implementation.
What I do wish is more transparency in InvenTree, that for instance we could go on to chat with the top 5 requested features or major fixes and settle on a solution agreed upon by the main concerned users, then decide on some sort of roadmap for implementation. Maybe one day Oliver will get enough time to setup something like this? :stuck_out_tongue: 

I'm also willing to help you out @sintech and others to push things to InvenTree because I also have a limited bandwidth but love to see new addition. I don't pretend I have even half the coding experience of Oliver but definitely knows where things are and how to manipulate them safely (sort of), so don't hesitate to shoot away any question!

**Comment by sintech** [comment]
> One thing that KiCad is badly missing is decentralized database of parts. I just couldn't cope (and still can't in some way) with the fact that each resistor (and other common parts) need to have a unique symbol in the library. So much efficiency waste in designing circuits!

I always use only one symbol for resistors (R for example) and when my design is ready for PCB I assign footprints depending on what size (0603, 0805, thru-hole) I need. But I see your point, in complex projects you have to have exact mapping between component model, symbol and footprint. Luckily I'm not at this point right now, but I'm moving towards it.

> What I do wish is more transparency in InvenTree, that for instance we could go on to chat with the top 5 requested features or major fixes and settle on a solution agreed upon by the main concerned users, then decide on some sort of roadmap for implementation. Maybe one day Oliver will get enough time to setup something like this? 😛

Sound like a good idea: some discord, slack or even telegram chat-room to discuss features.
But I agree with Oliver that a formal issue is a must-have before any feature implementation.

**Comment by matmair** [comment]
> 
> Sound like a good idea: some discord, slack or even telegram chat-room to discuss features. But I agree with Oliver that a formal issue is a must-have before any feature implementation.

@sintech I think the time difference between the core contributors and a lot of users (contributors in EMEA, users at least in EMEA and US, maintainer in AUS) makes any form of real-time / voice comms difficult. We will however try to use the discussions feature in GitHub for some kind of discussion platform for now. It is an experiment but feel free to use it!
