### ISSUE TITLE
Question about part selling

### ISSUE THREAD

**Issue by wengtad** [inventree/InvenTree#1472]
Use cases:
1. Create a sale order.
2. Add part with quantity 2.
3. Assign parts using serial number (SN001 and SN002).
4. Send to customer.
5. Return 1 of the part with serial number SN002 to a location (Office).
6. Send a replacement to customer with serial number SN003 (probably create a new sale order for this).
7. SN002 able to assign to another customer. (but currently is not working, it is not showing at Parts/Stock/Location)

SN002 only appear using search at the top menu bar. Although the stock tracking information showing "Returned to location Office", but it doesn't list at Parts/Stock/Location.

Just want to know the item sent to a customer and returned from them able to re-sell to another customer or not?
If support, may I know how to achieve it?

**Comment by eeintech** [comment]
@wengtad I was able to reproduce, the reason was that stock items associated to sales order returned as "no stock". I updated the  return from customer (eg. return to stock option) method to unset the `sales_order` field.
However, you will have to go into the Admin section to unset the sales order for the current stock items which were returned from customers already.
