### ISSUE TITLE
Add "last_updated_by" field to StockItem

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#1573]
- "last_updated" field exists, but no idea who did the update
- Needs to be recorded by form views
- Needs to be recorded in the API

Further, the "user" needs to be recorded when performing a number of various stock actions:

- Create a new "build output"
- Receive items against a purchase order
- etc etc

Might be cleaner to find an existing library that allows this in a "DRY" manner, and also integrates with the DRF API

Other models might also benefit from user "audit log" tracking...

**Comment by matmair** [comment]
@SchrodingersGat a great audit-log libary is https://django-auditlog.readthedocs.io/, has a minimal storage-footprint.

**Comment by SchrodingersGat** [comment]
@matmair oh that looks really nice.

Should we be using that for https://github.com/inventree/InvenTree/pull/1642 and also potentially the existing stock-item-history-tracking?

**Comment by matmair** [comment]
@SchrodingersGat I like the library because it is laser-focused on a json-based, tiny audit-log. You would have to shift all the rendering/translation-logic etc. away from the modal into views and signals.

I have not tried adding anything to it already so difficult to assess the effort. I personally like your implementation for stock-item tracking and would keep that.

**Comment by SchrodingersGat** [comment]
I think that the existing StockItemTracking model covers most of the intended functionality here, so going to close this out.
