### ISSUE TITLE
Purchase order clarification

### ISSUE THREAD

**Issue by sintech** [inventree/InvenTree#1832]
Since there is a lack of documentation about PO I would like to ask some (maybe silly) questions.

Prerequisites:
- Parts with filled manufacturer MPN and/or supplier SKU.

What is a suggested manual PO workflow?
- Create PO
- Use "Order Parts" dialog from Part to add a line to PO.
- (optional) Add order lines manually.
- Click "Place order"
- Make real order on supplier(s) website. Wait for shipping.
- Click "Receive Parts", fill actual received amount and status
- Click "Complete Order"

Is it a correct Upload File for Purchase Order UseCase?
- Create PO
- Make order on supplier website
- Receive parts and accounting + inventory docs
- Upload inventory sheet to PO. Automatically fill order item lines, quantities, prices.
- Click "Place order"
- Click "Receive Parts", fill actual received amount and status
- Click "Complete Order"

Questions:
- Currently it looks like I have to fill part price even before making real supplier order, is it correct?
- What if price has changed during making real order? But as I already clicked "Place order" I can't change item price.
- What is the purpose of "destination" field in order item line, if I have to choose "Destination" each time I click "Receive Parts"?
- Does it make sense to keep "Pricing ranges" in inventree because supplier prices could change pretty often.
- Does it make sense to fill order item price when parts are received (not before they are ordered)?

**Comment by eeintech** [comment]
Both workflows look correct to me.

> * Currently it looks like I have to fill part price even before making real supplier order, is it correct?

You don't have to do it before, after is fine too at the moment because "placing the order" is just updating your database locally, it does not interact with your supplier.

> * What if price has changed during making real order? But as I already clicked "Place order" I can't change item price.

That's a use-case not covered yet. You can however alter the status of the order in the Admin section :smiley: 

> * What is the purpose of "destination" field in order item line, if I have to choose "Destination" each time I click "Receive Parts"?

The destination is where all the received items will be stored as stock items when you mark the full order or some items as "received".

> * Does it make sense to keep "Pricing ranges" in inventree because supplier prices could change pretty often.

Still makes sense to have local data for reference even if not accurate / obsolete. But yes you're right supplier prices vary a lot, especially this year with the component shortage!

> * Does it make sense to fill order item price when parts are received (not before they are ordered)?

It could make sense to do it **after your supplier confirmed your order**, after that they shouldn't be able to change the prices. But it could be the quantities they send you are lower than expected.

**Comment by sintech** [comment]
Thank you @eeintech it is more clear now.

> The destination is where all the received items will be stored as stock items when you mark the full order or some items as "received".

But why then it is asking destination explicitly each time I do receive parts?
Also what does it mean "Select parts to receive against this order", how do I select?
![изображение](https://user-images.githubusercontent.com/10057327/126291923-874610f0-3f06-404f-adf3-8db71346cfec.png)

**Comment by eeintech** [comment]
@sintech If you have multiple parts in the order, it lets you the option to select a different destination (eg. a stock location) for each of them. You can also select a single destination if you click on the global receive button.

The "Select parts to receive against this order" in your case is a little confusing because you have only one part in your order. If you had a list of parts, that instruction means to fill out the "Receive" column with the number of parts received.

**Comment by sintech** [comment]
Ok, I have a feeling of issue here.
Screenshot above is from a click to "Receive line item". and "Destination" is required field, I can't submit form without selecting destination.
If I click global "Receive items" button the behavior is the same, I forced to choose destination. 
And in this case I expect that only `None` destinations will be rewritten by value from "Destination" field. While in reality they all got rewritten.
![изображение](https://user-images.githubusercontent.com/10057327/126316808-b36eb73b-134f-486e-9297-61859a4848b0.png)

**Comment by eeintech** [comment]
@sintech Yes you're right, if destination field is set on all items in the list, it should be okay to submit the form without selecting a choice in the "Destination" dropdown field. And it shouldn't be mandatory to select "Destination" if one or more items in the list don't have a destination set because stock item location is not mandatory. However, if the destination is selected in the form, it **should** overwrite any previous destination set as a shortcut to reset the storing location for all items. If left blank, the form should use the information from the destination column. Does it makes sense?

**Comment by sintech** [comment]
@eeintech sure it does. 
You described exactly what I expected from this form, except for blank destination, but it's ok since item location is optional.
Actually it would be great to have destination selector on every line of the table for further flexibility. It will be a step closer to bulk part operations.

**Comment by eeintech** [comment]
@sintech You can already select the destination for each line but it has to be done in the order item table, not in the receive item form.

**Comment by sintech** [comment]
Sure I can. 
But for 20 lines in order I have to click at least 60 times to change destination (not counting scrolling).
And it looks more logical to set part location on receive phase not before order is placed.
Anyway I will be happy if "Receive parts" is fixed according to https://github.com/inventree/InvenTree/issues/1832#issuecomment-883441266
Shall I make a new issue?

**Comment by eeintech** [comment]
No that's fine, should have time to fix the behavior soon :+1:

**Comment by eeintech** [comment]
@sintech Take a look at #1852 should be doing what you wanted :wink:

**Comment by sintech** [comment]
Thank you @eeintech !

**Comment by eeintech** [comment]
No problem, let us know if you find anything else!
