### ISSUE TITLE
Add possibility to disable unused functions

### ISSUE THREAD

**Issue by lettore** [inventree/InvenTree#1945]
I started using Inventree for my home inventory, there are many alternatives out there but none are simple to use.
The combination of the app for easy scanning codes and the server works really well.
For my use case I don't need the selling part and maybe also the buying part as I don't need to track every order I make, also because you need to add first a manufacturer and a seller for every part, this can be time-consuming.
I suggest then to add in the settings the possibility to enable every section as a module, like is structured Odoo for example.
This will make the interface cleaner and expandable, maybe with plugins.

**Comment by matmair** [comment]
@lettore not sure I understand what you mean; selling / purchasing only becomes available for a part if it is enabled for it. Have you disabled the functions for the part and do they stil show up? You can control the default settings for a new part in the settings.

We have several ways to do [plugins](https://inventree.readthedocs.io/en/latest/extend/plugins/) and I am working on a deeper integration but taht will take time as there are a lot of security concerns.

**Comment by lettore** [comment]
> @lettore not sure I understand what you mean; selling / purchasing only becomes available for a part if it is enabled for it. Have you disabled the functions for the part and do they stil show up? You can control the default settings for a new part in the settings.
> 
> We have several ways to do [plugins](https://inventree.readthedocs.io/en/latest/extend/plugins/) and I am working on a deeper integration but taht will take time as there are a lot of security concerns.

What I mean is not to see the sell button, the sales part in the main interface.
![image](https://user-images.githubusercontent.com/34779795/129002182-23bc6e84-e1f7-4b33-82ab-18f6cc0f84b9.png)
Many switches in every part that are not used if I'm not going to sell anything
![image](https://user-images.githubusercontent.com/34779795/129002491-485dcb95-b81e-4361-af5d-ca662a1ef8a7.png)
It's just for have a cleaner interface.

**Comment by eeintech** [comment]
@lettore "Settings" --> "User Settings" --> "Home Page" --> Disable both `Show outstanding SOs` and `Show overdue SOs`:

![image](https://user-images.githubusercontent.com/4020546/129077505-6843c5ca-66ce-401f-8e57-1e76aff6a8b6.png)

Home page will look like this:

![image](https://user-images.githubusercontent.com/4020546/129077554-7d0e503a-8435-4fe6-9407-035b024ca140.png)

**Comment by SchrodingersGat** [comment]
@lettore fair enough suggestion, I think it would be reasonable to at least be able to hide the "Build", "Buy", "Sell" tabs.

Obviously hiding these tabs would also disable lots of functionality on other pages too

**Comment by eeintech** [comment]
One way to disable them is with permissions. For instance, here is an example of group's permissions disabling view of POs and SOs:

![image](https://user-images.githubusercontent.com/4020546/129575740-529d047e-28f7-4d61-b846-df04daa6aba5.png)

And here is what the UI shows for a user of that group:

![image](https://user-images.githubusercontent.com/4020546/129575804-1aa28808-bbbd-4a02-89b0-c22a3e4f9b72.png)

**Comment by eeintech** [comment]
@matmair @SchrodingersGat I'm sorry to ask this stupid question: why are those settings at user level instead of server level? (ref #1999)

As I mentioned above, the "right" way to completely disable each section and functions is done through the permissions, which are controlled by the admin/superuser.
Now if a "normal" user wants to access those, it should be redirected to the "index" page or getting a "permission denied" message, but not the page it is trying to access.

What @matmair added in #1999 is nice but quite unnecessary or I am completely missing the point.
To me the idea would have been to let the user decide which section of the UI to show/hide, knowing that if the user re-enables it, that section will still be accessible.

We shouldn't add a parallel mechanism to the permission system that is just UI based, because it is a duplicate effort which adds more overhead like: compatible with permissions, always maintained for each UI updates, etc.

Instead, and if it makes it more user friendly, I would say that the permission matrix shown above can be ported to the server global settings. And **this** would be the system to rely on for truly disabling part of the UI/functions.

**Comment by matmair** [comment]
@eeintech I chose server-level as the possibility to disable nav-items for me seems to be an admin-level decision. And also because the admin would have to deal with users that disable nav-items and then get lost 😇.

We could easily move this to be user-based but I think that will bring more problems than necessary for our deployers.

**Comment by eeintech** [comment]
@matmair In that case, what was the intention behind disabling the interface globally, like in the permission system, instead of relying on the permission system, which does the exact same thing and is more secure because those disabled pages are **really** inaccessible?
