### ISSUE TITLE
[FR] Email notifications for low stock

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#2093]
When a part stock level falls below the "low stock" threshold, email any users who have "starred" that part.

**Comment by matmair** [comment]
@SchrodingersGat would you like to develop this or should we mark this as help wanted?

**Comment by SchrodingersGat** [comment]
Probably "help_wanted" on this one, otherwise I'll get to it eventually. Will wait for your SSO / email integration changes to be merged in first :)

**Comment by matmair** [comment]
> Probably "help_wanted" on this one, otherwise I'll get to it eventually. Will wait for your SSO / email integration changes to be merged in first :)

Yeah that is definitely going to be a 0.6.0 thing though - should be tested a lot before I break auth to all running instances 🤭

**Comment by rocheparadox** [comment]
Shall I take this up?

**Comment by SchrodingersGat** [comment]
@rocheparadox yes the order of those imports should be changed, although I'm not sure why it's breaking for you but passing for current CI tests?

**Comment by rocheparadox** [comment]
It is breaking for me because my code is apparently the only place where **Part** is accessed through **StockItem** right after the latter is saved in database. With the present order **StockItem** would be created using the fixtures but their respective **Part** would not be present at that point of time.
