### ISSUE TITLE
[FR] Looking for feedback on part parameters

### ISSUE THREAD

**Issue by Matthewmads** [inventree/InvenTree#2099]
**Is your feature request the result of a bug?**
No

**Problem**
I am working on setting up inventree for a commercial door supplier and I'm having some trouble understanding how parameters work in relation to stock. I would like to be able to enter stock and use parameters to identify various configurations found in our products. I'm able to add parameters from the admin page but when it gets to adding stock the process becomes cumbersome,

**Suggested solution**
The ability to add parameters when adding a new part from the same popup screen.

**Describe alternatives you've considered**
Still exploring, Have been experimenting with various part categories, Still have not found a method of organization that works well in this instance.

**Do you want to develop this?**
In the door and hardware field, a given product can have ten or more different configurations that may all fall under a given part number so this functionality is necessary. I would be happy to develop this a bit more but at this point I'm just trying to get my head around how parameters interface with parts. If anyone has thoughts and insight on how best to approach this I am more than willing to put together some videos and documentation to better explain it for future users (once I understand it better)

**Comment by matmair** [comment]
@Matthewmads thank you for the detailed question! I have to think about this one a bit and maybe @SchrodingersGat or @eeintech have ideas about this too!
Have you looked into variants at all? I tend to use variants for one base part with different accessories etc. The parten / child relationship often helps with reducing double entry.

**Comment by eeintech** [comment]
Two ways you could to do this, on top of my mind:
1. template part and variants 
2. categories parameters

Here is a brief explanation of both methods.

1. I would setup a template part with a set of pre-defined parameters, which values can be empty or set to default.
Then I'll go to the "Variants" tab and create all the different variants (eg. configuration) of that part/door, copying over all parameters from the template and filling them one by one.
With this method the relationship between the different configurations of each part/door is the **template** part.
However, it could be tough to find a specific configuration afterwards in the variants view.
If all the parts/doors are nested inside a category, you can use the parametric table as described below.
But you may end up with a huge amount of unique parameters if all parts/doors are nested inside one single category.

2. InvenTree let's you setup parameter templates for each category so that each time you create a part and associate it to a specific category it will come with a pre-defined set of parameters templates, which values can be empty or set to default.
With this method the relationship between the different configurations of each part/door is the **category**.
Bonus point, you can use the parametric tables to sort and filter configurations using the parameters values.
Navigate to a category view then the "Parameters" tab to use parametric tables.

After giving it more thoughts maybe the best would be a mix of both.
I would make sure that each category parameter templates are set right, then create a template part inside this category using the unique IPN. Then from there I would create variants. All variants would derive their parameters from the template part, and not from the category, because maybe you want to add an extra parameter to that part only. The next (template) part would have inherit from the category parameters too, which makes the copy-pasting of parameters become an automatic chore :smiley: 

> I'm having some trouble understanding how parameters work in relation to stock.

There is actually no link between part parameters and stock items. Only parts, manufacturer and supplier parts can have a set of parameters.

**Comment by Matthewmads** [comment]
@eeintech Thank you, This is very helpful! I hadn't considered using categories on such a granular level but it makes sense. I'll play with it some more and see where we end up. 

I'm still somewhat new to github, is there a place to post results of conversations like this? a "Best practices" type of section perhaps?

**Comment by eeintech** [comment]
> I'm still somewhat new to github, is there a place to post results of conversations like this? a "Best practices" type of section perhaps?

This could go into the documentation, as an example use-case scenario. But other than issues, I don't see where else.

**Comment by SchrodingersGat** [comment]
@Matthewmads did you require any more action on this one, or happy to cloes?

**Comment by eeintech** [comment]
In case OP has any more question, we should probably move to a discussion.
