### ISSUE TITLE
Add partial delivery feature

### ISSUE THREAD

**Issue by tse-tarn-france** [inventree/InvenTree#2187]
**Is your feature request the result of a bug?**
NO

**Problem**
When order is 10 parts and 5 are available, we would need to ship 5 immediatly and 5 later if needed, that's not possible at the moment :

![partial_delivery](https://user-images.githubusercontent.com/92796696/138174248-e13fb6d9-fca0-4e4b-94e3-44a9eab1488a.jpg)

**Suggested solution**
Do not close the order when partial delivery, consider beeing allowed to ship in multiple batchs, like build order can be.

**Describe alternatives you've considered**
Not Applicable

**Examples of other systems**
Every commercial or industrial inventory system can do that, this is a "MUST HAVE"

**Do you want to develop this?**
If I can, I'd like to try, but please assign a more experimented contributor to help me :-)
When I'm familiar to Inventree I will be able to contribute alone :-)

**Comment by SchrodingersGat** [comment]
Yes would definitely support implementation of this feature. This has also been raised in a previous issue. 

Working out how to implement this cleanly would be the major impediment.

I think that this would require the addition of a "Shipment" model. Multiple shipments can reference the same SalesOrder instance.

Then, instead of stock items being allocated against a SalesOrder directly, they are allocated against a shipment.

We would need to migrate any existing SalesOrder, so a single shipment would be created for any existing SalesOrder in the database.

Shipments can then be "shipped" with any amount of stock. User simply has to select "add new shipment" on the sales order page.

I'd like to stipulate that the implementation used only the API forms interface, rather than the (old) Django server side forms. Happy to provide pointers on this as the client side forms code is pretty complex. 

Feel free to ping me for any implementation discussions! I'd be really keen to see this feature added.

**Comment by afkiwers** [comment]
Will do!

**Comment by matmair** [comment]
@tse-tarn-france changes are in master
