### ISSUE TITLE
Multiple stock entries from separate purchase orders

### ISSUE THREAD

**Issue by lookme2** [inventree/InvenTree#2287]
**Describe the bug**
When I order the same part through purchase orders I get multiple stock entries even though I put them in the same location. 

**Expected behavior**
That I would get only one entry with the total of the two purchase order. This prevents me from being able to auto allocate this stock in a build order. 

**Version Information**
# Version Information:
InvenTree-Version: 0.5.3
Django Version: 3.2.5

Database: sqlite3
Debug-Mode: True
Deployed using Docker: False

**Comment by SchrodingersGat** [comment]
@lookme2 this is expected behaviour. If you receive two lots of stock against separate purchase orders, they **are** separate - with different tracking histories, etc. 

What you might be looking for is the ability to "merge" multiple stock items together - https://github.com/inventree/InvenTree/issues/346

This is something I've considered before (a *long* time before) but never implemented. It would be potentially tricky, especially to determine which stock item is the "main" one which keeps its stock history etc.

**Comment by lookme2** [comment]
@SchrodingersGat so I noticed this when I was allocating some parts for a build order.  It seems that you can over allocate a part.  I was thinking it was because of the multiple stock entries.  It only seems to be happening when you use the Auto Allocate button.  I will close this and play around with it some more.  Maybe I'm missing something.  Thanks
