### ISSUE TITLE
[BUG] 502 Proxy Error when uploading BOM

### ISSUE THREAD

**Issue by reilly-callaway** [inventree/InvenTree#2331]
**Describe the bug**
502 Proxy Error when uploading BOM

**Steps to Reproduce**
1. Upload bill of materials button in part
2. Upload CSV BOM
3. Match appropriate fields
4. Press "Submit selections" on step 2 of 3
5. Hangs for a while
6. Server returns 502 Proxy error

**Screenshots**
![Screenshot 2021-11-19 114132](https://user-images.githubusercontent.com/7870267/142519275-591f027b-41ab-450b-9285-bd661fd53d28.png)

**Deployment Method**
- [ ] Docker
- [X] Bare Metal

**Version Information**
InvenTree-Version: 0.6.0 dev
Django Version: 3.2.5
Commit Hash: 77dac2e62
Commit Date: 2021-11-15
Database: mysql
Debug-Mode: True
Deployed using Docker: False

**Comment by SchrodingersGat** [comment]
For reference, this is due to the way that the 'BOM import' process provides options to the user.

For each line in the BOM template, the server has to render *all* available parts which could be selected, and then order them according to how well they match.

For a dataset with thousands of parts this takes a *very* long time!

This will require a pretty major rework (incoming) to fix...
