### ISSUE TITLE
OPTIONS request doesn't return delete method

### ISSUE THREAD

**Issue by HelgiBergmann** [inventree/InvenTree#2381]
I don't know what is wrong, sorry for maybe stupid question but here we go=)
I created a basket detail API endpoint and serializer.
Now when I request OPTIONS its return me only PUT method in action without delete or get, I  really don't know what I done wrong
Here is 
https://github.com/HelgiBergmann/InvenTree/blob/32d39c60a43f4304cc666c09c321bd798de5cf5d/InvenTree/basket/api.py#L99

![image](https://user-images.githubusercontent.com/78436722/143899591-3ca158eb-7163-4a49-bc65-465cdeec0399.png)

**Comment by HelgiBergmann** [comment]
Kill all day to delete the basket....)

**Comment by SchrodingersGat** [comment]
I think that the issue here is that you have not assigned the new models to a permission group:

https://github.com/HelgiBergmann/InvenTree/blob/32d39c60a43f4304cc666c09c321bd798de5cf5d/InvenTree/users/models.py#L57

@matmair this makes me wonder how we are going to handle "permissions" in plugins where we don't want the plugin to have to touch base code.

Users must be in the correct "group" to have the required permissions to perform API actions such as "DELETE".

**Comment by matmair** [comment]
There is something more going on, I found that already but it still does not work right.

@SchrodingersGat my idea is that the plugin writer should run has_permissios before outputting. also the permissions can be mutaded after startup.

**Comment by HelgiBergmann** [comment]
@SchrodingersGat thanks
