### ISSUE TITLE
[BUG] Random timelines for updating Exchange rates

### ISSUE THREAD

**Issue by nwns** [inventree/InvenTree#2430]
**Describe the bug**
Because currency updates are done on App ready and as scheduled, the exchange rates will update whenever a worker is ready or when scheduled.

**Steps to Reproduce**
Every worker spawned by GUnicorn will run the app ready and update the exchange rates.  In #2241 this was manifesting as a serialization error.  Workers are re-spawned after 500 actions.  This gets worse when running in a cluster that has transient workers (such as Google Kubernetes Engine with Preemptable nodes).

**Todo**
[ ] - Does Q-Cluster trigger app ready for every worker?
[ ] - Does Q-Cluster trigger app ready for every task?
[ ] -  #2241 raised concerns about changing the exchange rate while calculations are going on.

**Expected behaviour**
We need to discuss what is the actual expected behaviour of currency exchange.

**Deployment Method**
- All platforms.

**Version Information**
Master (and probably released versions as well)

**Comment by nwns** [comment]
**My Initial thoughts**
We should probably remove the exchange update from app ready and allow it to only run either explicitly by the user from Admin or automatically using Q-Cluster on a scheduled set by the user.

**Comment by matmair** [comment]
@nwns the current implementation should only update if the exchange rates are too old or the base currency changed; this seems to be broken in some way. If we fix this would this be a solution for this issue?

**Comment by nwns** [comment]
It probably would. But at the same time, that is in part what I am trying to figure out with this issue:
* Figure out how the dynamic currency exchange rates are actually being used by user?
* What is the issue that the automatic currency exchange rates solving?
* Do we have a problem currently with the exchange rates changing unexpectedly?
* Should the exchange rates change without the user being involved (either by scheduling the change or manually by entering the numbers or by pressing an "update now" button).

**Comment by matmair** [comment]
@nwns we have practically no way to communicate with users. Only a small minority (judging by pulls on the python library, master, docker and the traffic on some random code tests I have on my profile) actually interacts with the issues and we have nothing in regards to telemetry.



> * Figure out how the dynamic currency exchange rates are actually being used by user?

I and local users I know use it to keep the exchange rates somewhat in step with the market. A few days can make a good difference if you order enough.



> * What is the issue that the automatic currency exchange rates solving?

Forgetting to hit the update button could be quite expensive while updating the rates on each order will slow down the whole process a lot and put unfair strain on a free API.



> * Do we have a problem currently with the exchange rates changing unexpectedly?

If they are updated often enough the difference should be small enough. Most of my suppliers update around once a day so something in that range seems to be a good middle ground. Could be configurable if you want, I am happy with the current implementation (except for the bug with starting up - my last attempt at fixing failed).



> * Should the exchange rates change without the user being involved (either by scheduling the change or manually by entering the numbers or by pressing an "update now" button).

Absolutely, I would forget all the time and I do not think that most users read through all settings (I think, we do not know due to no user survey or telemetry).
