### ISSUE TITLE
Build allocation ideas

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#292]
Show list of 'remaining' allocations - this quickly shows what you need to buy or build or whatever.

Filter 'allowable locations' to take stock from. e.g. only allow stock items from /work/office/* or from /* for all stock items

**Comment by jnewlands** [comment]
More fine grained process of what a 'build allocation' is - currently you put parts in (and can overallocate if you want), but then the parts disappear. Need a way of managing:

- Getting a full reel from stock, putting it in a box. Can't allocate all of it to the build or it will disappear. Manually moving it from one location to the temporary location currently doesn't have any structure (e.g. a page prefilled against the BOM).
- Filtering stock items in the build allocation by an existing location (so that e.g. an existing parts kit can be pulled from).
- Receiving parts back from a supplier - some mixture of surplus parts and the output of the build. May want to explore approximate quantities - a reel having some rough minimum quantity is often all the info that is needed.
- A build might create parts that then need to be serialised, but briefly exist in a state without one.

This may look like a more generic 'location to location' transfer that can be prefilled against certain models (e.g. a BOM or a salesorder).

**Comment by SchrodingersGat** [comment]
https://github.com/inventree/InvenTree/compare/master...SchrodingersGat:take-from?expand=1 adds the ability to specify where parts are taken from for a build.
