### ISSUE TITLE
[FR] Improved Dashboard System / Index Page Improvements

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3062]
The current "home page" needs a major overhaul and should show information pertaining to the logged-in user.

For example a technician should be able to see all the build  orders assigned to them, basically their "assigned tasks".

Instead of *boring* tables, some "dashboardy" widgets which are information dense.

The dashboard will also be exposed to the plugin interface, so custom dashboard "widgets" can be added.

*Open for ideas...*

**Comment by SchrodingersGat** [comment]
@eeintech @matmair @maksimstojkovic any ideas here? What would you like to see as a "dashboard" when you log into InvenTree?

**Comment by matmair** [comment]
@SchrodingersGat the option to load a lot less data at the beginning would be nice. So everything loads faster and that there are fewer API requests.

**Comment by maksimstojkovic** [comment]
@SchrodingersGat possibly a similar bar to the page-actions menu which allows sales/purchase/build orders to be created directly, before reloading into the page of the said order. It could be debated whether the inclusion of the bar would consume too much screen real estate, but in the future it could be modified to include other frequently used actions (ideally this is a data-driven decision).

**Comment by eeintech** [comment]
I would vote for a "recent activity" feed:
- part added, by which user and when
- part supplier update, by which user and when
- BoM recently validated, by which user and when
- stock updates, by which user / PO / SO and when it was updated
- BO status updates, by which user and when it was updated
- etc.

**Comment by feurer98** [comment]
I think you can never please everyone.
That's why I would give the user a possibility to design it himself. 
As a reference like MyPage from Openproject: [Docs](https://www.openproject.org/docs/getting-started/my-page/)

Maybe just keep this option in mind and then introduce it on a testable frontend.

**Comment by matmair** [comment]
> I would vote for a "recent activity" feed:
> - part added, by which user and when
> - part supplier update, by which user and when
> - BoM recently validated, by which user and when
> - stock updates, by which user / PO / SO and when it was updated
> - BO status updates, by which user and when it was updated
> - etc.

Nice idea. Could be a pretty expensive database operation without caching thought.

**Comment by maksimstojkovic** [comment]
Thoughts on a single-page scrollable dashboard with tiles/widgets that can be enabled/disabled?
I find that a fair bit of the information available on screen in the existing dashboard is not used when deciding to navigate to a specific order.

For example, it only makes sense to show pending sales orders (whether outstanding or overdue) in the dashboard, and can be listed in a tile/widget sorted by due date or value (unsure if price filtering is currently available). Overdue orders could be distinguised using a red flag on the left of the order for example, similar to the existings `fa-calendar-times` icon (alternatively a simple red rectangle could be used).

Additionally, the SO reference, customer and description (and maybe scheduled shipment date) are the only pieces of information I've ever used to quickly navigate to an order from the dashboard. If I required further information to determine what SO I was looking for, it would make sense to navigate to the `Sales Orders` page first and use the search functionality there.

As a visual reference, below is an example Xero dashboard which uses a similar page layout to what I've described above. Instead of accounting data, the dashboard tiles should reference the different order types, stock item warnings, and part subscriptions.

![dashboard-uk](https://www.starfishaccounting.co.uk/wp-content/uploads/2016/12/dashboard-uk.png)

Ultimately the goal is to provide key information and minimise the number of clicks to view said information.

**Comment by matmair** [comment]
I think it is highly dependent on the type of user. A workshop operator only cares about their build orders and maybe what parts are low in stock while someone in accounting or logistics might be more interested in getting orders in/out.
These dashboard ideas all seem great but I strongly suggest to create a clear outline of the architecture before we spend significant dev time on it.

**Comment by matmair** [comment]
Needs #3901
