### ISSUE TITLE
[FR] Support SVG images for parts/companies

### ISSUE THREAD

**Issue by miggland** [inventree/InvenTree#3074]
**Problem**
The URL copy function for images is amazingly simple - great tool. However, it does not work for SVGs.
Many companies use SVG logos on their websites. SVGs are standard in web development nowadays.

**Suggested solution**
Add SVGs to the list of supported formats. The display should not be more difficult than PNG/JPG images..

**Describe alternatives you've considered**
Downloading, converting to PNG, and uploading - works, but takes much longer.

**Comment by matmair** [comment]
Webp support was already added - that seems to be the way the big distributors go. Feel free to add svg to the supported list, I see this as low priority.

**Comment by SchrodingersGat** [comment]
@miggland supporting `svg` would be actually much more complicated than you might expect at first thought, due to the way that django handles image files.

Essentially as `svg` is a non-raster image format, which is not supported by [pillow](https://pypi.org/project/Pillow/) then it cannot be supported the the [Django ImageField](https://docs.djangoproject.com/en/4.0/ref/models/fields/#imagefield)

There are also potential security concerns supporting `svg` files

Refs:

- https://code.djangoproject.com/ticket/14092
- https://medium.com/@7WebPages/how-to-have-svg-allowed-as-an-image-for-django-rest-framework-52772b972167

SVG support will require some careful consideration before implementing.

**Comment by miggland** [comment]
Yes the problem is obviously larger than I expected. If there is no easy way to add an automatic conversion either, drop this. After all, it is a minor inconvenience!
