### ISSUE TITLE
[FR]Special characters restriction in category names

### ISSUE THREAD

**Issue by martonmiklos** [inventree/InvenTree#3358]
"Hi folks,

I tried to copy over the category tree from a webshop called TME via API but I realized that some of the categories cannot be added because they have illegal characters in the names.
By looking the code I found the limitation:
https://github.com/inventree/InvenTree/blob/master/InvenTree/InvenTree/validators.py#L84
What is the motivation behind of them? Having category names like 'D/A converters' or comma separated category names could be useful I think in many cases.

**Comment by SchrodingersGat** [comment]
@martonmiklos this character limitation was introduced a long while ago, and many changes to the category structure have occurred since then. I think this could be re-assessed, certainly *some* of these characters could be allowed.

Recently we addressed some XSS issues which means we could probably be a little less restrictive here.

@matmair thoughts? I think some of these characters at least could be allowed now,.

**Comment by matmair** [comment]
@SchrodingersGat we should test for XSS after removal but I see no reason fir the general bleach implementation beeing enough.
