### ISSUE TITLE
Required for build order logic error

### ISSUE THREAD

**Issue by gunstr** [inventree/InvenTree#3653]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

If I not have misunderstood the intention with the "Required for build orders" page I think there is a bug. It's provides a great summary that I use to place purchase and build orders but it happens now and then that I find parts in the list where I already have enough quantity.

I found issue #2399 related to the the same page but it's more for adding additional info - for sure good suggestions that would  make procurement easier.

### Steps to Reproduce

One recent example:

1. I have one part with a quantity of 30 in stock
2. Allocate 20 for a new build order
3. The part stock info looks like this
![image](https://user-images.githubusercontent.com/41468206/188735665-f21cb8b0-872e-407c-9127-d15b05231152.png)

All OK, but the part is anyway listed as required in the "Required for build orders" page with stock quantity 10.

### Expected behavior

The part in the example should not be listed as required in the summary view

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.9.0 dev
Django Version: 3.2.14
Commit Hash: ef12a834e
Commit Date: 2022-08-01
Database: mysql
Debug-Mode: True
Deployed using Docker: False

**Comment by SchrodingersGat** [comment]
@gunstr thanks for reporting. Looking at this, it seems that this "required quantity" feature needs a lot of attention. There a few different ways in which it is currently broken.

The main reason that relates to your issue here is that the `required_parts_to_complete_build` method does not take into account the quantity currently allocated against the build:

https://github.com/inventree/InvenTree/blob/ea60cdc6a8a7eaa5a445148f5067e5c0137c5377/InvenTree/build/models.py#L1066

Also, this is a very expensive calculation currently, and needs some attention to make it more efficient.

**Comment by SchrodingersGat** [comment]
Not stale

**Comment by matmair** [comment]
@SchrodingersGat should this be tagged for `0.10.0`?

**Comment by gunstr** [comment]
Adding the fix I have done if it helps anyone. No guarantees it's correct and complete, but at least for my use case it does the job....

I changed line

https://github.com/inventree/InvenTree/blob/34bb40d4398c18efec65c59ac476b30e62044a43/InvenTree/build/models.py#L1080

to

`required_quantity_to_complete_build = self.remaining * bom_item.quantity - self.allocated_quantity(bom_item)`
