### ISSUE TITLE
Quantity 0 in a BOM 

### ISSUE THREAD

**Issue by RichiSeitz** [inventree/InvenTree#3683]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

When I've a BOM and have for example some Screws inside, I would set the quantity at 0. Because I don´t like to count every single screw but I want to have the screws inside the BOM. So I can see that I have to use this screw but it don´t change autom. the stock when I build a Part from this. I will put the whole package from screws (f.e. 5pcs) in the stock. So I can book the screws by my own in and out. This is much easier for such parts as counting every single piece.

### Suggested solution

You have only to enable the possibility to set 0 at the quantity.
We, offer you some money for this feature, because we love your project. 

### Describe alternatives you've considered

There are no alternatives for me.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
Sounds doable - maybe behind a settings flag?
@SchrodingersGat do you want to tackle this?

**Comment by SchrodingersGat** [comment]
@RichiSeitz this sounds similar to an existing PR - https://github.com/inventree/InvenTree/pull/2890

Here, instead of setting quantity to zero (and thus losing information) we add an extra "consumable" flag which means that the items are required for the build, but do not need to be tracked in the build allocation process.

This way you keep the quantity information (which is still valuable) but you don't have to keep individual counts of things like tape, glue, etc. You can manually do that when you finish a reel, or a bottle, or whatever.

Does this proposed solution sound acceptable for your usecase?

> We, offer you some money for this feature, because we love your project.

If you would like to sponsor the project (which is greatly appreciated) you can check out our [sponsorship page](https://github.com/sponsors/inventree)

**Comment by RichiSeitz** [comment]
Oh perfect, I don´t see this,sorry. Yes such a flag is also working for me for shure. Thank you very much, Inventree is really nice to use :)

**Comment by SchrodingersGat** [comment]
@RichiSeitz merged into master now - check it out :)

**Comment by r0l1** [comment]
@SchrodingersGat great thanks! We'll wait for the next stable release.
