### ISSUE TITLE
Add query-count validation as part of CI / Unit Testing

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#3716]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### Problem statement

Many API queries have been refactored to ensure that we don't run into the dreaded [1 + N query problem](https://medium.com/doctolib/understanding-and-fixing-n-1-query-30623109fe89#:~:text=TL%3BDR%3A%20The%20N%2B,%E2%80%9CHow%20to%20fix%20it%3F%E2%80%9D)

Primarily these refactors / improvements have been to ensure that the same number of DB queries are performed, independent of the number of results returned

### Suggested solution

We should add some unit tests to ensure that the number of results does not alter the number of DB queries, using the [assertNumQueries](https://docs.djangoproject.com/en/4.1/topics/testing/tools/#django.test.TransactionTestCase.assertNumQueries) function

### Describe alternatives you've considered

Leave as is

### Do you want to develop this?

- [X] I want to develop this.

**Comment by matmair** [comment]
@SchrodingersGat do you want to do this?

**Comment by SchrodingersGat** [comment]
I'd like to tackle this, I have some specific areas I want to profile first.

**Comment by tombola** [comment]
Would this be of any interest?: https://github.com/jmcarp/nplusone

I only just found it, and on initial look it appears to log rather than raise exception, but I thought it might be a good way to profile more generally.

I have not yet used myself, was just looking for a way to avoid that kind of issue without having to predict that it might be an issue, and I like that this is abstracted into middleware.

**Comment by matmair** [comment]
For what it is worth: Sentry detects and reports n+1 issues and as far as I know both @SchrodingersGat and I have instances running with it.
