### ISSUE TITLE
[FR] Add typecasting to certain settings

### ISSUE THREAD

**Issue by matmair** [inventree/InvenTree#3725]
Typecasting in the settings for:

Looks like there are 6 envs that need to be int (that I can find)
- [x] INVENTREE_LOGIN_CONFIRM_DAYS
- [x] INVENTREE_LOGIN_ATTEMPTS
- [x] INVENTREE_EMAIL_PORT
- [x] INVENTREE_DB_PORT
- [x] INVENTREE_CACHE_PORT
~~INVENTREE_WEB_PORT~~

_Originally posted by @stavros-k in https://github.com/inventree/InvenTree/issues/3655#issuecomment-1259866326_

**Comment by matmair** [comment]
`INVENTREE_WEB_PORT` is a setting for gunicorn - not shure how to do that and if that is even necesarry.

**Comment by stavros-k** [comment]
> `INVENTREE_WEB_PORT` is a setting for gunicorn - not shure how to do that and if that is even necesarry.

It seems to accept strings fine, (as i use a different internal port and works)

**Comment by Ornias1993** [comment]
It's a bit of an odd issues, because environment variables are inherently strings. There is no int environment variable, that simply does not exist on Linux.

What I think is happening, is that some dependencies or code portions, are more forgiving with this than others. Which explains why the type is only triggering issues on some environment variables.

Typecasting should fix this on the source of origin, which is totally fine :)
