### ISSUE TITLE
InvenTree droplet not available in DigitalOcean marketplace

### ISSUE THREAD

**Issue by JustusRijke** [inventree/InvenTree#3873]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

The InvenTree droplet is not available on the DigitialOcean marketplace.

The referral link in the repo is broken: https://marketplace.digitalocean.com/apps/inventree?refcode=d6172576d014

The direct link works: https://marketplace.digitalocean.com/apps/inventree

But when clicking [Create InvenTree Droplet](https://cloud.digitalocean.com/droplets/new?onboarding_origin=marketplace&appId=118690138&image=mjmair-inventree&activation_redirect=%2Fdroplets%2Fnew%3FappId%3D118690138%26image%3Dmjmair-inventree), it seems the image is missing and is no (longer) available for deployment from the marketplace.

### Steps to Reproduce

click the links ;-)

### Expected behavior

being able to deploy the InvenTree droplet

### Deployment Method

- [ ] Docker
- [ ] Bare metal

### Version Information

N/A

**Comment by matmair** [comment]
@JustusRijke the droplet is currently not available due to updates in its structure (switching to the new installer mainly + some security and maintainability tests and upgrades). It will be back when those are done. Under 50 deployments a month and 100 concurrent installs are deployed using this method so it takes a backseat compared to upgrades to the installer and the 0.9.0 install.

It is curious that you are still able to see the image at all, I deactivated it fully.

**Comment by JustusRijke** [comment]
I posted the wrong link, the documentation page is still available (including a deploy link): https://docs.digitalocean.com/products/marketplace/catalog/inventree/

**Comment by matmair** [comment]
I raised a support ticket with them, not sure how long that will take to remove.
