### ISSUE TITLE
Sorting buttons (small arrows) in the parameter table do nothing in parameter columns

### ISSUE THREAD

**Issue by SergeoLacruz** [inventree/InvenTree#4204]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### Describe the bug*

There are small buttons above the table cols in the parameter view:
![para](https://user-images.githubusercontent.com/10836099/211891414-6b013af8-b7b5-4295-9bc3-07ab11411a5e.png)

The left most ones in the "part" column sort the content as expected. The other ones do not work. 

### Steps to Reproduce

1 Goto parameter view
2 Make sure that there are several lines in the table
3 try to use the sorting buttons in the right most columns, 

### Expected behavior

I would expect that all arrows sort the table based on the column

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

InvenTree Version 	[0.10.0 dev]
Development Version
	Commit Hash	4bfc1f742
	Commit Date	2023-01-11

**Comment by matmair** [comment]
That seems to be a bug, we will have to look into that before the next release. Thanks for the report @SergeoLacruz

**Comment by bloemp** [comment]
@matmair I've traced this to the part/api.py. The table gets filled by PartList class, but parameter data for the parts is added by the PartSerializer and subsequent PartParameterSerializer. 
Also part.js has the following text on line 1587:
` // TODO: Re-enable filter control for parameter values`

I'm afraid my knowledge of python/django is lacking and I can't figure out how to solve this... but hopefully this information can save you a bit of time when trying to solve this.

**Comment by matmair** [comment]
@bloemp the bug is ordering control, that section is about filter control.
The API endpoint for the part parmeter list endpoint is defined here:
https://github.com/inventree/InvenTree/blob/e730b5c24ce88b7b3d72d39903815359b5b66fdb/InvenTree/part/api.py#L1676-L1707
The frontend code that defines the table is located here:
https://github.com/inventree/InvenTree/blob/e730b5c24ce88b7b3d72d39903815359b5b66fdb/InvenTree/templates/js/translated/part.js#L1119-L1221

I will have to debug a bit more to get insights why this is not working, seems fine to be tbh.

**Comment by bloemp** [comment]
@matmair I'm pretty sure the frontend code is located here: 

https://github.com/inventree/InvenTree/blob/e730b5c24ce88b7b3d72d39903815359b5b66fdb/InvenTree/templates/js/translated/part.js#L1542-L1631

I think part of the problem is on line 1575 where we are creating custom field names that don't seem to be recognized by the backend as part of a model.

https://github.com/inventree/InvenTree/blob/e730b5c24ce88b7b3d72d39903815359b5b66fdb/InvenTree/part/api.py#L1609-L1666

**Comment by matmair** [comment]
@bloemp I was under the impression that sorting is done in the frontend only.
