### ISSUE TITLE
After updating to 0.10 stock do not load

### ISSUE THREAD

**Issue by AntoWkill** [inventree/InvenTree#4403]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hello,
When i try to see the stock part /part/ server "charging" without output

Here the screen

https://i.ibb.co/ZSXX0KR/Screenshot-2023-02-23-alle-19-51-25.png

All other area where part are, load without any problem (like: /part/category/1/# )

### Steps to Reproduce

1) Login
2) Go to "part"

### Expected behaviour

Load all the part

### Deployment Method

- [ ] Docker
- [X] Bare metal

### Version Information

0.10.0

**Comment by AntoWkill** [comment]
I found the bug.

The problem is there are a file without "Product category", before 0.10 was possible. From inventree admin i assign a category to all product and now works.

**Comment by simonkuehling** [comment]
@AntoWkill did you try a force-reload of the website? Since you mentioned that you just updated InvenTree - sometimes javascripts or other assets might have changed on the server but do not get reloaded right away in the browser due to caching…
Ctrl+Shift+R does a forced refresh on most Browsers - or try opening a Private Window in your Browser to test if it works from there or not…

**Comment by SchrodingersGat** [comment]
Looks like it is related to https://github.com/inventree/InvenTree/pull/4369

I'll back-port this fix to the 0.10.x branch

**Comment by SchrodingersGat** [comment]
@AntoWkill glad you got it working on your end :)
