### ISSUE TITLE
Selling part to remove stock

### ISSUE THREAD

**Issue by IsThisNameGoodEnough** [inventree/InvenTree#476]
When creating a part you can flag it as "Sellable", but there doesn't seem to be a way to remove stock via a sale.  The only work around I see is to go into the stock page for the part and select "Take from stock".  Is there another method of marking a sale?  Would be nice to have a process so that stock notes are consistent.

**Comment by SchrodingersGat** [comment]
The "sellable" flag speaks to a feature that has not been implement yet - namely the ability to sell stock.

Currently there is the concept of a "PurchaseOrder" for buying parts. But not yet a "SalesOrder" for selling them. 

I hope to implement this soon but there's a lot of extra complications because you now need to keep track of which stock items are at which customer, etc, etc...

**Comment by IsThisNameGoodEnough** [comment]
Ah, understood.  I figured it was a future feature.

One thought regarding a stop-gap solution.  Perhaps a simple SalesOrder page that just has optional input fields for customer name (no retention like Suppliers) and invoice number, and a drop down to allow you to choose a Part/StockItem.  Confirming the SalesOrder would perform a stock out and place the customer name and invoice number in the stock out notes.  This would give a way to keep consistent records, and the customer name and invoice number would still be searchable.

I can see the value of a more fleshed out SalesOrder process, but my guess is that most people would be relying on their accounting software for invoices and customer info, and would use InvenTree just to keep the link of invoice number to batch or serial number.
