### ISSUE TITLE
Translation string letter-casing

### ISSUE THREAD

**Issue by LavissaWoW** [inventree/InvenTree#5044]
As the project stands, it's currently running ~114 duplicate translation strings generated due to differing word capitalisation on the source string. 

As an example: 
msgid "Transfer stock"
msgid "Transfer Stock"

I presume this is just down to the writing style of each developer. But, just to be sure: Are there any situations where we need to have this distinction? If not, I was thinking about adding some sanity checks to translations to weed out these duplicates. For anyone wanting to translate InvenTree, having to type 100+ extra strings due to differences in capitalisation amounts to quite some time. (Speaking from exp. here)

Would it perhaps be relevant to have a "standard" way to write out translatable strings?

**Comment by matmair** [comment]
Due to the slow-growing nature of the code base, this will always happen, especially with the many places translations go.
Also, language is very much a cultural thing and different between people. You can try to add checks but be warned that there are several repos that contribute translations to Crowdin so I am not sure how successful you will be.

Also please use the issue templates, it is hard to categorise and not overlook things if they do not get tagged for triage.

**Comment by SchrodingersGat** [comment]
@LavissaWoW I agree in principle but might be hard to develop a single "standard". There are places you want to capitalise (e.g. titles of forms) and other places not.  Maybe we could run the text through a dynamic filter when displaying as a title, to capitalise every word, and then we enforce that only the first word of translated strings are capitalised?

**Comment by wolflu05** [comment]
I don't think every language capitalize like this rule.

**Comment by SchrodingersGat** [comment]
@wolflu05 I was wondering whether that might trip us up.

**Comment by LavissaWoW** [comment]
@wolflu05 That's true.
You'd need a lot of context to understand where the string is used. 
Atm, every sting is just referenced by its place in code. That's not a bad idea for us code literate people. 

If more context could be given without having to add things to code, that would ofc be perfect. But I haven't looked Into Crowdin, Django and parsing yet.

**Comment by wolflu05** [comment]
Tbh this translations by code ref was new to me until I first seen it at InvenTree. Before I was using json files that contained the translations by (nested) keys. But this had a lot of overhead and was much more complicated because as a dev you had to create that entry in the default lang yourself and search before if there is already a similar string.

**Comment by LavissaWoW** [comment]
Expanding a bit on context here:

A `#Translators: [some explanation]` comment above a Python translatable string will include it as context in the .po file, and subsequently on Crowdin.
In HTML/JS, `{% trans "foo" context "bar" %}` also provides context for a string.

**Comment by LavissaWoW** [comment]
Looking into pre-commit hooks. Made a quick example:
`INFO: You did not provide context for the translation at: ..\InvenTree\InvenTree\company\models.py:749`

You could get a notice that you failed to contextualise your translation, but it wouldn't fail CI?

**Comment by matmair** [comment]
@LavissaWoW context sounds interesting, should we make a testrun?

**Comment by LavissaWoW** [comment]
@matmair What did you have in mind?
