### ISSUE TITLE
Backup of media files exceeds worker timeout

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5108]
### Discussed in https://github.com/inventree/InvenTree/discussions/5078

<div type='discussions-op-text'>

<sup>Originally posted by **Fluxus00** June 20, 2023</sup>
Hello guys, 

i activated the automatic backup option in the InvenTree configuration. The database backup is working fine, a new backup is created daily, but the backup of the media files does not seem to work as intended. In the past week only one file, containing the media files, had been created. So my question is now, is there an option/ special condition i am missing, or is it working as intended?

Best regards
</div>

**Comment by T0jan** [comment]
I also run into this problem. A workaround for me for now is to schedule "manual" backups with crontab. a small script starting the virtual environment and call `invoke backup` called by a cronjob is all that is needed.

**Comment by SchrodingersGat** [comment]
not stale

**Comment by SchrodingersGat** [comment]
Not stale, but needs some thought

**Comment by SchrodingersGat** [comment]
Still not stale,

**Comment by T0jan** [comment]
not stale

**Comment by T0jan** [comment]
@SchrodingersGat The bot prompted me to check on this again. Since my initial comment here I got allocated hardware with a bit more single core performance for my InvenTree VMs. The manual backups are now a lot faster (around 2min instead 5+ before) and this seems right at the edge for the worker timeout in the auto-backup now. The media backup-file gets now generated occasionally, but is never complete. The file size varies between 50 and 150MB instead of 260MB for a manual backup and the try to restore these backups ends with a:

```
EOFError: Compressed file ended before the end-of-stream marker was reached
```
I guess the worker now kills the backup process right before it finishes on its own. 

So this is most likely a setup question here and not really something you can fix in the code (except increasing the timeout) or what do you think?

**Comment by SchrodingersGat** [comment]
We could add a manual timeout just for this task - this could even be exposed as a setting, potentially?

**Comment by T0jan** [comment]
@SchrodingersGat could be an idea, but the question is, if it's really necessary. We now have it running on a machine with a lot single core power and it still isn't running reliable while not many other people seem to have this problem. So I assume it is more a problem with how the VM was setup and not with inventree.

**Comment by SchrodingersGat** [comment]
@T0jan any further action required on this, or happy to close it out?

**Comment by T0jan** [comment]
@SchrodingersGat as nobody else reporter here and my workaround works for me I don't see any reason to keep it open.
