### ISSUE TITLE
Add support to scan digiKey partlabels

### ISSUE THREAD

**Issue by davrex** [inventree/InvenTree#5119]
Add support to scan digiKey partlabels QR for easier adding of stock items.
Scan QR 
find matching part,
populate the quantity
![20230628_223507](https://github.com/inventree/inventree-app/assets/2648476/7ba75c43-2fba-4c0f-a2c2-afbe81581ee1)

**Comment by SchrodingersGat** [comment]
not stale, still a good idea!

**Comment by 30350n** [comment]
Hey! I'd be interested in helping to implement this. I've already managed to get barcode scanning working by adding a barcode plugin, but in the current state this isn't really useful for checking in parts after receiving an order.

For me personally, the ideal workflow would be to:
1. Add the Part/ManufacturerPart/SupplierPart definitions to Inventree automatically after ordering, via something similar to [Ki-nTree](https://github.com/sparkmicro/Ki-nTree) (I'm currently working on my own simplified version of this. Ideally this would also have to be accessible from within the InvenTree interface directly).
2. Add the Order by providing the BOM from the manufacturer. (This already works pretty well, although I've had some issues with part value detection).
3. Once the order is received: Scan in each items barcode, directly followed by a Stock Location barcode, to automatically mark the item as received and create the new Stock item.

For me personally, I'd like to be able to do 3. quick and easily via the App. I'm thinking of adding a Scanning Action in the Purchase Orders section, like this:
<img src="https://github.com/inventree/InvenTree/assets/34186858/6e997012-0a54-44f4-a7bf-3021d311ae46" width="300">

The information present in the 2D barcode could then be used to automatically figure out the Order etc.

I'm not sure though how an implementation for the InvenTree web interface would like.
Would be very happy to get some feedback/more ideas on this topic! :)

**Comment by matmair** [comment]
I am currently actively working on 3) here #5500 and have ideas for 1) in #3791

**Comment by matmair** [comment]
Implementing this in the App shouldn't be too difficult, the source code is here: https://github.com/inventree/InvenTree-app

**Comment by 30350n** [comment]
> Implementing this in the App shouldn't be too difficult, the source code is here: https://github.com/inventree/InvenTree-app

Yep, I'm already on it! Main issue is I've never messed with app development/dart before really, but it looks pretty straight forward, so I'll see what I can come up with.

**Comment by matmair** [comment]
> > I am currently actively working on 3) here #5500 and have ideas for 1) in #3791
> 
> Great! I've seen #5500 earlier, but wasn't sure if it'd apply to this, so thanks for confirming that ^^
> 
> I've already managed to get my own less bloated version of Ki-nTree going, [here's](https://gist.github.com/30350n/eaec22389a42cbe6df00ec38063ca0fc) a gist of the (still very messy) WIP code. Looking at #3791, I'm guessing that's supposed to implement the neccesary foundations/api for allowing "part importing plugins" to exist in the first place right? And your actual implementation for DigiKey lives in [inventree-digikey](https://github.com/matmair/inventree-digikey/tree/v1)? If so I'd be happy to try and integrate my part importing code into there, if desired.

#3791 is not ready for prime time right now but the idea is to move all the vendor APIs to plugins and into mainline Inventree - so that access to them can be exposed both to WebUI and API (with perks like simple configs over various machines, rate watching etc). It would be great if we could have a good digikey plugin once that is done but it is to early to hold anyone of their development.


> Yep, I'm already on it! Main issue is I've never messed with app development/dart before really, but it looks pretty straight forward, so I'll see what I can come up with.

Setting up the environment is the most time-consuming task there, dart itself is IMO very easy if you know a bit of JS.

**Comment by SchrodingersGat** [comment]
@30350n thanks for commenting, your approach sounds really nice. I have put some brief thought into this previously, and your overall process seems good.

I would add another simple step: `4) Assign the hash of the ECIA barcode to the newly created stock item`. This means that any successive scans will use the internal barcode plugin and directly identify the newly created stock item.

Additionally, scanning the barcode should `5) Return the newly created stock item` - so that the app / UI / api / can immediately reference the new item.

Writing this as a back-end plugin means that it might be able to work out-of-the-box with the app without any change to code - and certainly any required changes could be made pretty simply.

**Comment by 30350n** [comment]
Thanks a lot!

4) is a great idea!
> Writing this as a back-end plugin means that it might be able to work out-of-the-box with the app without any change to code - and certainly any required changes could be made pretty simply.

This is not really possible I think (as discussed [here](https://github.com/inventree/InvenTree/pull/5509#issuecomment-1707912024)).

**Comment by matmair** [comment]
I think that we should implement the more complex checking/receiving actions in P UI/React. Multi-step stuff in one API-call might be a bit intransparent. When done in the UI we can (for now) keep the state just in the client and make our life a lot easier. This could for example be done with #5500 as a suggested action if an order barcode is detected

**Comment by SchrodingersGat** [comment]
@davrex please note that this has now been implemented as a first-class feature. The InvenTree app can now directly scan barcodes for incoming digikey orders!

Closed in https://github.com/inventree/InvenTree/pull/5509
