### ISSUE TITLE
exporting 'category' field adds description

### ISSUE THREAD

**Issue by gitjoost** [inventree/InvenTree#512]
Example CSV that fails to import:
id, name, description, keywords, category, IPN
1, TLV316IDBVT, IC OP AMP CMOS RR 10MHZ SOT-23, OpAmp, “electronics/semi/ic/linear”, 500000001
2, TLV2316IDGKR, IC OP AMP GP 10MHZ 8VSSOP, OpAmp, “electronics/semi/ic/linear”, 500000002

Error: Cannot assign "'“electronics/semi/ic/linear”'": "Part.category" must be a "PartCategory" instance.

invenTree appears to assign incorrect columns to the imported data set showing: 

ROW | ERRORS | ID | NAME | IS_TEMPLATE | VARIANT_OF | DESCRIPTION | KEYWORDS | CATEGORY | IPN
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

Adding the two missing columns IS_TEMPATE and VARIANT_OF lines up the imported data correctly but still fails with the same error as mentioned above.

**Comment by SchrodingersGat** [comment]
Ok I think I have worked this out now - see https://github.com/inventree/InvenTree/pull/524

After a lot more reading on how the import/export plugin works, the admin interface is now working really well. You can export data cleanly, and now the import works too!

- Any row with an ID matching one in the database will be UPDATED
- Any row with a blank or unknown ID will be CREATED
- Any row with invalid ForeignKey data will show an error and must be fixed in the external file
