### ISSUE TITLE
Import requires 'column id'

### ISSUE THREAD

**Issue by gitjoost** [inventree/InvenTree#513]
Importing fails with error:
Line number: 1 - "Column 'id' not found in dataset. Available columns are: ['name', 'description', 'keywords', 'category', 'IPN']"

The csv file used for import must be fixed with an extra column 'id' and integer number to permit importing.

The 'id' column requirement should be removed imho

**Comment by SchrodingersGat** [comment]
This is now fixed in the linked PR.

You will still need an "id" field - but this actually makes sense. For each row, the database needs to decide if the row already exists and needs updating, or is a new record and needs to be added.

For each row you wish to create, simply leave the id field blank / empty.

A good way of doing this is to first export the existing data into the format of your choice, and then use this as a template for re-importing data.

Please give the latest version a go and see if it works for you!
