### ISSUE TITLE
Is there a way to make this multi tenant

### ISSUE THREAD

**Issue by option-greek** [inventree/InvenTree#556]
Hi,
I'm wondering if there is a way to make this multi tenant so that multiple merchants can manage their inventory from the same hosted site.
If this functionality is not there, could you let me know which modules are good places to look at for adding this functionality.

Regards,
OG

**Comment by SchrodingersGat** [comment]
Hi OG, 

To confirm what you are looking for, you want multiple installs at the same domain like:

* acme.inventree.domain.com
* veridian.inventree.domain.com

Are these tenant sites going to be hosted locally (i.e. on your server / intranet / etc) or externally (e.g. AWS / etc)

**Comment by option-greek** [comment]
Hi,
Yes (multiple installs on the same domain - mapped to a subdomain)
Tenant sites will be externally hosted (probably on GCP compute engine/GKE if that makes sense)

Use case is Amazon seller central kind of model focused more on for inventory management.

Thanks,
OG

**Comment by SchrodingersGat** [comment]
I think then that the best approach is to have separate containerized installs. Each instance of InvenTree does not need to know about the other installs.

Installing multiple copies of InvenTree on the same system without containers is possible but more care is needed. Each instance would need a separate database, for example, so for system-wide databases (e.g. MySQL) you would need to ensure each db is uniquely named.

**Comment by option-greek** [comment]
Thanks Oliver.

One more question: Are the labels in various places configurable. For example from 'Part' to 'Product' (or even multi language support - 'Part' but in a different language).

**Comment by SchrodingersGat** [comment]
Currently they are not translatable. However, django (the web framework that inventree is written in) supports a translation layer - https://docs.djangoproject.com/en/2.2/topics/i18n/translation/

Basically for each part of the text you want translated, instead of writing the raw text (e.g. "Part") you write something equivalent to "Translate('part')".

It is a feature I wish to add - but do not have time for at the moment. I would happily accept assistance on this front - perhaps this is something you would be able to help me work towards?

**Comment by option-greek** [comment]
Sure Oliver. If we implement this, I will be sure to push the changes back here.

**Comment by SchrodingersGat** [comment]
I've opened a new issue regarding translation - https://github.com/inventree/InvenTree/issues/559 - so I'll close this one out now.
