### ISSUE TITLE
Implement method for uninstalling plugins

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5637]
Once a plugin is installed, it cannot be "uninstalled" via the web interface. Requires a sysadmin with pip knowledge.

Following on from https://github.com/inventree/InvenTree/pull/5624 it would be a good feature to add. Including rewinding any custom schema migrations if the plugin implements the app mixing.

**Comment by wolflu05** [comment]
I think it would be a good idea to add a little switch to remove all data including database tables, ... on the uninstall dialog instead of doing this without asking. That way one could also use this for reinstalling another version. Eg switch from a git plugin to a pip plugin. 

Additionally, we could also invoke a function on the app Mixin for uninstalling where the developer could clean up anything custom he did.

**Comment by SchrodingersGat** [comment]
This has actually been implemented now - at least in the PUI interface.
