### ISSUE TITLE
[CI] Fix sponsors action

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5799]
Ref: https://github.com/inventree/InvenTree/pull/5794

 Intent is to make a PR to update `README.md` whenever the project gets a new sponsor

**Comment by matmair** [comment]
@SchrodingersGat as far as I can see the thing fails because it tries to push to `master` directly and our branch protection rules forbid that. I might be overcautious but do we want anything pushing to master before a `maintainer` role-holding person at least skimms through it?
Seems like a security risk - considering we deploy `master` regularly automated to the demo server and development users just run master.

**Comment by matmair** [comment]
I can fix it probably pretty fast; I just want to discuss the merits of having it run like this. A flow like with Crowdin makes IMO more sense.

**Comment by wolflu05** [comment]
I would vote for creating a PR against master if there are changes on sponsors.

**Comment by SchrodingersGat** [comment]
I agree it sho
