### ISSUE TITLE
[bug] currency exchange rates are broken

### ISSUE THREAD

**Issue by T0jan** [inventree/InvenTree#5831]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

Hi,

After updating from 0.11.x to 0.12.8 last week I noticed that my currency exchange rates are now not working properly anymore:

* if USD is the base currency every others currencies exchange rate is there and the exchange rate to USD is 1 as expected

![image](https://github.com/inventree/InvenTree/assets/22519396/fab51509-b2ba-4a64-9d82-3a9f94529c52)

* if any other base currency is selected, the exchange rate to USD stays at 1 and the exchange rate for the base currency, which would be expected to be 1, is missing (EUR is the base currency for the picture below)

![image](https://github.com/inventree/InvenTree/assets/22519396/ab74f31d-ac8b-4e8b-8d3a-45ef9a01a342) 

as the bug seems not to be present on the demo site, I suspect something went wrong on the version conversion of the database. If you could lead me to the entry7file which could need fixes to get this back to how it should be I would appreciate this greatly. 

### Steps to Reproduce

not sure how it ended up this way. could be related to the upgrading process, I have the same behavior on two instances, one came from 0.12.dev from before the release of 0.12.0 and one from 0.11.3 as written above.

### Expected behaviour

* USD should have an exchange rate != 1 for every currency except USD
* all other currencies should have an exchange rate entry of 1 to them self for background and API purposes

### Deployment Method

- [X] Docker
- [ ] Bare metal

### Version Information

# Version Information:
InvenTree-Version: 0.12.9
Django Version: 3.2.19
Commit Hash: d2a313b
Commit Date: 2023-10-19
Commit Branch: 0.12.x
Database: postgresql
Debug-Mode: True
Deployed using Docker: False
Platform: Linux-5.15.0-75-generic-x86_64-with-glibc2.35
Installer: GIT

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

### Please verify if you can reproduce this bug on the demo site.

- [ ] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
I can confirm that this bug exists on `0.12.8` - but appears to be ok on `master`

**Comment by Mimosa-oceanis** [comment]
Hi, I think I have an issue who is probably linked with this one. 
Since we've updated from 12.1 to 12.8. If we enter the price of a piece in an other currency than the default one. The supplier price in the pricing overview and the price range are not calculated.

![Capture d’écran 2023-11-02 à 14 23 33](https://github.com/inventree/InvenTree/assets/65179484/8fc55b89-9307-4d40-ba55-f46cf7dda2b1)
![Capture d’écran 2023-11-02 à 14 23 23](https://github.com/inventree/InvenTree/assets/65179484/b88589f1-8f82-4fd9-aab8-9cec3ce29578)

Here is the information on our system: 

# Version Information:
InvenTree-Version: 0.12.8
Django Version: 3.2.19
Commit Hash: a7487ff
Commit Date: 2023-10-03

Database: postgresql
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-4.19.0-24-cloud-amd64-x86_64-with-glibc2.36
Installer: DOC

Active plugins: [{'name': 'InvenTreeBarcode', 'slug': 'inventreebarcode', 'version': '2.0.0'}, {'name': 'InvenTreeCoreNotificationsPlugin', 'slug': 'inventreecorenotificationsplugin', 'version': '1.0.0'}]

**Comment by T0jan** [comment]
@Mimosa-oceanis I suspect your base currency is not USD? I think the missing exchange rates for all other currencies even as they are always 1 is the problem here as well. InvenTree apparently needs both exchange rates, even for the base currency, to calculate the value and as one of them is missing the task probably falls silently in one of the background workers. I can see the same behavior if I try to update a price via the python API.

**Comment by Mimosa-oceanis** [comment]
@T0jan Yes you are right, my base currency is CHF (Swiss franc). 
It seems I have the exchange rate updated. At least in the parameter it looks it is.
Or is it only an issue with USD. 

![Capture d’écran 2023-11-02 à 15 09 09](https://github.com/inventree/InvenTree/assets/65179484/d9051ae3-af23-4fd1-ba43-b5ba6b646ceb)

**Comment by SchrodingersGat** [comment]
Ok, see PR incoming in https://github.com/inventree/InvenTree/pull/5843

**Comment by SchrodingersGat** [comment]
`0.12.9` has just been released - will take a bit to build, but then should be available with this bug fix

**Comment by T0jan** [comment]
@SchrodingersGat thx for the quick fix :)
