### ISSUE TITLE
[Proposal] Change "SKU" to "Supplier Part Number"

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#5984]
SKU may not be the most widely understood shorthand, perhaps we should change the references to this to "Supplier Part Number", which is more explicit and lends itself better to translation..

**Comment by vr-varad** [comment]
@SchrodingersGat it would be easy if u elaborate your problem

**Comment by SchrodingersGat** [comment]
Our community translators have raised the point that SKU (Stock keeping unit) is not used in other languages and is hard to translate.

At this stage looking for input from other project contributors. Whether or not we should change, or keep the same. If we do change it would require changing a lot of translated strings throughout the code base. 

Alternatively we could leave it as "SKU" and encourage translators to use "supplier part number"

**Comment by vr-varad** [comment]
@SchrodingersGat  
![ss](https://github.com/inventree/InvenTree/assets/114755221/3676bea8-49f7-4811-9b46-5b07d566e3e9)
is the issue closed?

**Comment by vr-varad** [comment]
Stick with "SKU" if it's familiar and embraced by your community, ensuring consistency and avoiding unnecessary disruption. However, recognize the potential translation challenges and consider introducing "supplier part number" alongside "SKU" for additional clarity, especially in diverse linguistic contexts. Evaluate the global understanding of "SKU" within your user base; if it's not universally recognized, a more widely accepted term might enhance accessibility. Acknowledge the effort involved in updating translated strings and weigh the impact on your team. Ultimately, seek input from your community to ensure the chosen approach aligns with their preferences and maintains effective communication.

**Comment by LavissaWoW** [comment]
SKU is an industrial term, so I guess a lot of laymen don't really have a relationship to the term.
It is however a proper term, and I don't see the harm in using it. 
We could add help texts to SKU where it's used? Hover-based help buttons, basically, where the term can be explained.

In addition, to help translators, I've looked into translation contexts. These allow you to define a context for the word being translated. This can be used to elaborate or explain what the translator is supposed to be translating. 
The word "Stock" is a perfect example. Given no context at all, this would often times be interpreted by an external translator as being a share of a company bought at a stock exchange, rather than referring to your inventory.

Looking past SKU, there's also IPN and BOM that are acronyms we're injecting directly into translations. To further complicate things, some of these are used directly as acronyms, but not when spelled out. 

In my language at least, I'm not sure how to handle the translations of BOM and SKU depending on if they're acronyms or spelled out. But that's me trying to not cater directly to only us, but making the translation more general.

**Comment by LavissaWoW** [comment]
For backend translations, like in models etc, it looks to me that:
`_('String to translate', 'Helpful context to explain')`
Will produce a note in Crowdin With "Helpful text to explain" on the gived string

For Classic UI:
`{% translate "String to translate" context "Helpful context to explain" %}`
Will give the same

For PUI I'm not sure, though. I don't know the inner workings of the `t` function yet.

**Comment by SchrodingersGat** [comment]
@LavissaWoW thanks for the tip about translation context - might be a sufficient approach to add some context to the difficult strings. I'll try it out first with a simple PR

**Comment by SchrodingersGat** [comment]
Closing out , will proceed with additional context for the translated texts
