### ISSUE TITLE
Completing a 'build' doesn't subtract parts used from stock

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#600]
I created a part that is assembled. I then made a BOM with a single resistor used 10 times. I then built 40 of them and the stock of the resistors did not go down. The stock of the resistors should have gone down by 400

**Comment by SchrodingersGat** [comment]
You need to "assign parts" to the build for the parts to be depleted. This allows you to:

- Select which location to take the parts from (in the case they are stored in multiple locations)
- Create the build without all parts allocated (e.g. you have some parts that are not "in the system")
- Add in "overage" if necessary (e.g. remove 415 parts because 15 were wasted).
- Order any parts that are required but not in stock

![image](https://user-images.githubusercontent.com/10080325/71663798-b2762980-2daa-11ea-892f-d9dc54fb0e7c.png)

![image](https://user-images.githubusercontent.com/10080325/71663820-cd489e00-2daa-11ea-8c3f-314138e3d783.png)

**Comment by a7hybnj2** [comment]
Is it like this so you can pick the stock location when allocating? I am trying to think of an example of when you would build a part from other parts and not want to remove the parts used in assembly from stock.

Maybe there should be a slider on the 'complete build' that reads something like 'no parts were allocated for this build are you sure you want to continue' ::SLIDER:: or maybe `if parts allocated - parts used != 0` "you did not allocate parts correctly" or something.

**Comment by SchrodingersGat** [comment]
> Maybe there should be a slider on the 'complete build' that reads something like 'no parts were allocated for this build are you sure you want to continue' ::SLIDER:: or maybe if parts allocated - parts used != 0 "you did not allocate parts correctly" or something.

I like both these ideas - anything that improves the user experience here is good.

**Comment by a7hybnj2** [comment]
Just was looking over my old open issues and I am going to close this one because many improvements have been made in this area.
