### ISSUE TITLE
QUESTION: How do I BOM out a PCB Panel?

### ISSUE THREAD

**Issue by a7hybnj2** [inventree/InvenTree#661]
If I have a PCB that is built. In the bom is the PCB Panel of 10 to make that PCB. Do I add the panel to the bom as QTY = .1? What if there are 6 on a panel then it would not be a clean decimal number. Can the QTY field take fractions?

**Comment by SchrodingersGat** [comment]
I would personally just specify the PCB itself as part of the BOM, and ensure that the "in-stock" quantity is 6x the number of panels. But this approach may not be what you prefer. 

The quantity field cannot handle fractions, only decimal numbers.

**Comment by a7hybnj2** [comment]
@SchrodingersGat Let me make sure I understand your idea.  
So I have 125 panels of 8 = 1000 boards (once broken up).  
I have both the 8panel as in inventory item used by the finished individual boards BOM.  
Are you suggesting that I just make the 8panel inventory as 1000 instead of 125?  

Or is there some way to specify the 8panel as an assembled part that consists of 8 individual boards? or what?

**Comment by SchrodingersGat** [comment]
> Are you suggesting that I just make the 8panel inventory as 1000 instead of 125?

Exactly. There are always going to be situations that aren't as "neat" as you might like but InvenTree needs to remain reasonably generic. 

Another example would be a "bottle" which comes in boxes of 100 - clearly the "unit" here should be the individual bottle, otherwise you'd have to subtract them .01 "boxes" at a time.
