### ISSUE TITLE
[PUI] Update to Mantine v7

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#6813]
### Charts

Mantine 7 introduces charts: https://mantine.dev/charts/getting-started/

This looks to be a much better suited charts implementation which will match our visual style, and is much easier to use than charts.js

### Datatable

Updating would also allow us to make use of v7 of mantine-datatable (which we use extensively throughout the project).

We should make this switch soon if we are going to do it, while we are still "unreleased" on the new interface

**Comment by matmair** [comment]
@SchrodingersGat v7 changes the way styling works fundamentally and makes the building pipeline a bit more complicated, the upgrade is not to be underestimated. This is why I pinned it.

**Comment by SchrodingersGat** [comment]
Ok, understood. Is it worth the effort in your opinion? We do need to get charting integrated, which is the main driver here. Also do not want to be left behind in terms of datatable features.

**Comment by wolflu05** [comment]
Yes, I recently started using mantine v7 in a new project. Basically the complete styling system changed. They now suggest to use css modules (the createStyles/useStyles hook is no longer available). Personally I don't really like the way of how they work because there is no typing for variables like the theme colors anymore, because they're now using css variables.

The closest we can get is using [vanilla-extract](https://mantine.dev/styles/vanilla-extract/). That way we can still define our style with the help of ts types.

But I definitely think we should migrate to v7 at some time and not stay with v6 because that doesn't get any new features or updates anymore.

**Comment by LavissaWoW** [comment]
Might I just chuck in, for consideration, Apache Echarts: https://echarts.apache.org/en/index.html

**Comment by matmair** [comment]
At some point, we will have to upgrade but for now, which of the numerous solutions to retain similar styling functionality is the right one is unclear to me. This and plugin integration are probably the biggest locking ToDos for switching to PUI fully.

**Comment by XanderLuciano** [comment]
Since we don't use `useStyles()` in many places, dropping that support doesn't seem like a large terrible task to resolve.

Component props changing is a bit more of a headache though. I'll keep my eyes on this issues. I haven't used V7 yet either, so I'm not certain the lift required to complete the upgrade.

**Comment by wolflu05** [comment]
I think this can be closed now, since #7028 is merged now. Or do we want to keep that open for things that broke during that update? But I think that should be a new issue.

**Comment by SchrodingersGat** [comment]
Happy to close, thanks for the reminder @wolflu05
