### ISSUE TITLE
[PUI] Allow opening of top tabs and side tabs in new window

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#7271]
InvenTree version 0.15.1 | 196

The new interface looks great ! Apart from the features that will be implemented in #5212, the only feature I am missing is the ability to open a new tab with a CTRL+click (or middle click) on the UI elements. When I am browsing for parts, I like to go through the list and open every part in a new tab. I also like to be able to open new tabs with the navbar elements (parts, stock, ...).

EDIT : looks like CTRL+click is working on part list, but not on navbar. Middle click never works.

_Originally posted by @Valdoise in https://github.com/inventree/InvenTree/discussions/5328#discussioncomment-9495669_

**Comment by wolflu05** [comment]
That issue leads me to another idea, what about opening the parts detail page, but only in a drawer with about 90% width so that one can easily step through parts, check things and quickly continue with the next part. (We could do that for every tables detail page). But if we open the url directly (so we're not coming from a table), then we open the part in 100% without loading and showing the table first

**Comment by SchrodingersGat** [comment]
> That issue leads me to another idea, what about opening the parts detail page, but only in a drawer with about 90% width so that one can easily step through parts, check things and quickly continue with the next part. (We could do that for every tables detail page). But if we open the url directly (so we're not coming from a table), then we open the part in 100% without loading and showing the table first

Do you mean when selecting an item in a table, specifically?

**Comment by wolflu05** [comment]
Currently when clicking on a line in a table, a new page opens. What about showing that in a 90% drawer instead, like we do on most tables in the admin center.

**Comment by Valdoise** [comment]
So I compared "legacy" UI and platform UI :
![image](https://github.com/inventree/InvenTree/assets/62264027/d6e1363b-ea6d-46ec-a859-400145a9bf36)
![image](https://github.com/inventree/InvenTree/assets/62264027/bf16e9dc-21e9-49fc-b964-a750c0b7489c)

To me, the difference in behavior of the middle click is caused by the absence of the URL in the name of the part in the new UI version.

@wolflu05 I'm more skeptical about a drawer. My workflow with the old UI was really : 
- Go through the table and open in a new tab every part of interest
- Cycle over the tabs

This allowed me to quickly cycle between interesting components once they were opened in tabs, instead of searching again in the table.
