### ISSUE TITLE
[PUI] Reduce duplicate queries

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/InvenTree#7597]
Platform interface currently performs a number of duplicate API queries which slows down page response time.

![image](https://github.com/inventree/InvenTree/assets/10080325/0d5fd556-ef43-409e-8963-27651dbe1a76)

**Comment by wolflu05** [comment]
We could define some small amount of caching time in tanstack query. That way when the same query is performed multiple times in the loading process, only the first is send to the server.

**Comment by matmair** [comment]
@SchrodingersGat could this be the permission check page? I have various issues with multiple requests since that merged

**Comment by matmair** [comment]
@wolflu05 How would this cache be invalidated once things change because of a query? Is there a mechanism for that?

**Comment by wolflu05** [comment]
> I have various issues with multiple requests since that merged

Me too. I think Oliver is already working on a fix in #7598. Hope that gets merged soon.

> How would this cache be invalidated once things change because of a query? Is there a mechanism for that?

We could set the (frontend) caching to a small time like 1s to 5s and also invalidate the entries after the user creates or updates something. Since we have all in generic components, that shouldn't  be to hard. There is documentation for invalidation [here](https://tanstack.com/query/v4/docs/framework/react/guides/query-invalidation). Detailed documentation for how caching works can be found [here](https://tanstack.com/query/v4/docs/framework/react/guides/caching).

**Comment by SchrodingersGat** [comment]
This has been largely addressed, enough that I am happy to close out this issue. Will continue to monitor for any query issues
