### ISSUE TITLE
Wrong item purchase price when using Enter

### ISSUE THREAD

**Issue by dieselburner** [inventree/InvenTree#7600]
### Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find a similar issue

### Describe the bug*

When entering purchase order item I use tab and enter keys, and as a result I believe the Auto Pricing is not automatically unchecked when I hit enter after updating item price. As a result, added item loses manually entered price and shows calculated pricing as per supplier price breaks.

Add item:

![Screenshot from 2024-07-09 12-23-43](https://github.com/inventree/InvenTree/assets/1078344/dad55ad2-2bf2-4215-8a11-4ce79639ff3a)

Result:

![Screenshot from 2024-07-09 12-19-17](https://github.com/inventree/InvenTree/assets/1078344/f4f31b10-df2f-4cfd-8238-d92a33fe0dff)

### Steps to Reproduce

1. Create purchase order
2. Hit _Add Line Item_
3. Select _Part_
4. Use Tab key to navigate to _Puchase Price_
5. Enter required price
6. Hit Enter key

### Expected behaviour

Manually entered purchase price is shown in entered item.

### Deployment Method

- [X] Docker
- [ ] Package
- [ ] Bare metal
- [ ] Other - added info in Steps to Reproduce

### Version Information

# Version Information:
InvenTree-Version: 0.15.4
Django Version: 4.2.12
Commit Hash: fa1a9da
Commit Date: 2024-06-16

Database: sqlite3
Debug-Mode: False
Deployed using Docker: True
Platform: Linux-3.10.108-x86_64-with
Installer: DOC

### Please verify if you can reproduce this bug on the demo site.

- [X] I can reproduce this bug on the demo site.

**Comment by SchrodingersGat** [comment]
@dieselburner thanks for reporting.

**Comment by rocheparadox** [comment]
@SchrodingersGat , I will try to fix this.

**Comment by SchrodingersGat** [comment]
Thanks @rocheparadox

**Comment by rocheparadox** [comment]
This issue arises due to the underlying model of the events of forms as defined in forms.js

https://github.com/inventree/InvenTree/blob/76f8a2ee9e42c383383c846b892d1874720ac089/src/backend/InvenTree/templates/js/translated/forms.js#L1634

The jquery documentation for the *change* event goes as follows

> For select boxes, checkboxes, and radio buttons, the event is fired immediately when the user makes a selection with the mouse, but for the other element types the event is deferred until the element loses focus.

Hence, the purchase price is not updated until it loses the focus (using mouse or tab key). Now, changing the 
`el.change(function(){})` to `el.on('input', function(){})` 
will fix this issue but I am a bit skeptical about it since this will affect all the other elements throughout the codebase. I can add a new trigger call _onInput_ like the _onEdit_ is defined in forms.js
https://github.com/inventree/InvenTree/blob/76f8a2ee9e42c383383c846b892d1874720ac089/src/backend/InvenTree/templates/js/translated/forms.js#L301
Since this is more of a design decision, I would like to get your opinion, @SchrodingersGat and @matmair . Thanks.

**Comment by SchrodingersGat** [comment]
@rocheparadox I think your second simpler approach would be best. However please note that we are in the middle of a huge refactor of the front-end interface (moving to react).

So, new features for the legacy UI will not be given priority. If you can provide a low-risk bug fix for this, I'm happy to review and merge that. However if you can also check functionality on the new interface that would be appreciated !

**Comment by rocheparadox** [comment]
@SchrodingersGat, Sure. I will stick with the second option then. I am not a frontend developer and have little to no experience with react. Since, I am familiar with js, I thought I would fix it. I am looking forward to contribute more in python.
