### ISSUE TITLE
[FR] Open PDF attachments in the browser instead of downloading

### ISSUE THREAD

**Issue by Bart97** [inventree/InvenTree#7894]
### Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### Problem statement

I would like to store datasheets as attachments for each parts. When I do so, the datasheet gets downloaded to my PC, which quickly makes a mess in the downloads folder.

### Suggested solution

It would be much easier if I could view the file directly in the browser instead of downloading an opening it. As far as I know it's a matter of configuring the webserver to add an additional header to each response containing an attachment PDF:
`content-disposition: inline; filename="MyFile.pdf"`
This could be toggled by a configuration flag, so people cen pick their preferred behavior.

Update: Unfortunately it's not as simple as changing the webserver config. The link itself has the `download` attribute in html:
`<a href="/media/part_files/1/TS78L00_M2206.pdf" title="/media/part_files/1/TS78L00_M2206.pdf" download=""><svg class="svg-inline--fa fa-file-pdf fa-w-12" title="" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="file-pdf" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512" data-fa-i2svg="">SNIP</svg><!-- <span class="fas fa-file-pdf" title=""></span> --> TS78L00_M2206.pdf</a>`

### Describe alternatives you've considered

I've considered patching the webserver configuration myself, but I'd rather use a clean official release.

### Examples of other systems

It's done this way on most suppliers' sites like Mouser and TME.

### Do you want to develop this?

- [ ] I want to develop this.

**Comment by matmair** [comment]
Due to how browsers handle windows context this is currently not possible securely with untrusted inputs that can contain code (ie. PDF datasheets, HTML or similar). We handled attachments as requested in the past and received very simple Proof of Concept files that completely broke/exposed instances.

If you check out how big vendors handle this, there are 2 ways:
1) you "safeguard" contents (mouser)
2) host on a separate domain (webshop is www.digikey, media is mm.digikey and "PDF" datasheets are jpg in a custom renderer on www.digikey.com/en/htmldatasheets/*)

both are not feasible if we want to keep deployment simple and use the dev resources we have available economically.

**Comment by SchrodingersGat** [comment]
@Bart97 the response by @matmair above outlines our approach. We are erring on the side of good security practice.

You will note that our standard proxy setup forces the "attachment" attribute to anything served from the `/media/` path:

https://github.com/inventree/InvenTree/blob/7178b95657a59b16d175e01148b7e25b37f84f5c/contrib/container/Caddyfile#L51

**Comment by Bart97** [comment]
Okay, I wasn't aware that this may create security issues. In such case this issue can be closed.
