### ISSUE TITLE
Add Test Result should offer a list of Test Templates

### ISSUE THREAD

**Issue by rco3** [inventree/InvenTree#859]
When adding Test Data to a Stock Item, the popup 'Add Test Result' should not present an empty box; it should present a list of Test Templates associated with the Stock Item's Part. Optionally, depending on the user's authorization level, the option to add a new Test Template at this stage may be appropriate.

I would be interested in trying to implement this one (and many more), but I need a little bit of pointer to know where to start.  It's probably faster for @SchrodingersGat to make this change directly.

**Comment by SchrodingersGat** [comment]
@rco3 this is a good idea - just a little difficult to implement at the moment.

Currently if you want to add a test result against a particular test, you can click the "+" button associated with that test:

![image](https://user-images.githubusercontent.com/10080325/84092067-aff2bc80-aa39-11ea-951b-28385b94b852.png)

Adding multiple options to the test name field is possible but some changes to the back-end are required to enable forms to display drop-down selection boxes that also allow custom user input. Essentially this is because if a choice-box is displayed, the back-end code checks that the provided data is one of the displayed choices (and returns an error if it is not).

So it would require some custom code to override this behavior (in special circumstances).

**Comment by rco3** [comment]
I hadn't noticed the + on a given test.  That will suffice to eliminate the typo error problem, and workflow can include that.

Given the difficulty involved and the above solution, seems pretty low-priority to me.

Thanks.
