### ISSUE TITLE
[Question] How to install pre requisite programs on windows?

### ISSUE THREAD

**Issue by JunkyardCat** [inventree/InvenTree#873]
how does one install these prerequisite on windows os natively

g++
make
libpango-1.0-0
libpangocairo-1.0-0

im assuming that python-dev and python3-pip (pip3) is already installed when one has python already setup. if not can anyone tell me how to install

**Comment by SchrodingersGat** [comment]
Hey @JunkyardCat installing under Windows is possible, but trickier, as *nix systems offer a much richer set of command line tools.

I would strongly suggest you install either [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) or [MinGW](http://mingw.org/) and then follow the installation instructions as per normal.

Otherwise, you'll have to run the individual commands which are contained in the makefile, and ensure that any required system-level binaries or libraries are installed - the setup process will give an error message if a particular requirement is not met.
