### ISSUE TITLE
Stock Location Does Not Appear

### ISSUE THREAD

**Issue by LarryJoy** [inventree/InvenTree#890]
Oliver,
Looking at Parts, a particular IPN of mine, click on Part goes to the Main screen Details tab. The Default Location is "Office/Box 2 - Parts Box 2". Click on Stock tab, lists part but "Location" column says "No stock location set". What is going on?
Clicking on the part on this screen, it goes to Supplier Part screen, pricing tab. Click on Edit supplier part icon, there is no place to enter stock location.
Seems like there is two places to enter stock location, in the Parts and in the Stock. How do you edit the stock location when in the Stock versus when in Parts?

**Comment by SchrodingersGat** [comment]
There are a couple of concepts here which I think are being conflated - understandable, given the currently lacking docs.

## Part / Default Location

The "Part" concept has a *Default Location* which is nominally where and *Stock Items* for that part will be stored (unless otherwise specified)

## Supplier Part

The "Supplier Part" does not have a default location or a stock location

## Stock Item

A stock item is a particular instance of a Part. This is what has an actual location associated with it.

When looking at the stock table, click on the "stock" column to go to the actual stock item:

![image](https://user-images.githubusercontent.com/10080325/89161577-20d7d000-d5b6-11ea-872d-4f19b0709c3a.png)

Then once in the StockItem view you can transfer or adjust the stock using the stock actions drop-down:

![image](https://user-images.githubusercontent.com/10080325/89161673-449b1600-d5b6-11ea-8623-493502bf182e.png)

**Comment by SchrodingersGat** [comment]
@LarryJoy did this explanation make sense? Are you Ok with me closing this issue now?

**Comment by LarryJoy** [comment]
Oliver,
It's been a month since I submitted this problem and you did reply the next day. I remember that your explanation did work and I don't know why i didn't get back to you and let you know. Yes, you can close this issue. Thanks again.
--Larry
