### ISSUE TITLE
Add ability to link items (i.e. specific pcb with a specific daughter board)

### ISSUE THREAD

**Issue by Kedarius** [inventree/InvenTree#918]
It would be great if the user would be able to easily link two or more items together. Something like a build but "weaker". 
For example I have a PCB with connector for Raspberry Pi. I have the PCB and the RPi as stock items. Now I need to say that this RPi has been put into that PCB....

**Comment by SchrodingersGat** [comment]
@Kedarius this is a great idea, and one that I have been trying to work out how to do "simply".

Currently the `StockItem` model has a field `installed_in` which is set-aside for this exact purpose. However the "business logic" side of things has not been worked out yet.

What features / implementation details would be of particular interest to you here?

**Comment by wolffam** [comment]
@Kedarius , if this functionality was added around the build object, would that work for your use case?  
I am envisioning a workflow where you stock components, make a build with the assembly level part, and the components that are allocated then "belong_to" that build. Then we can include functionality to "modify a completed build" which will let the user uninstall and install new items into that same build and the "belongs_to" identifier will change appropriately.
I'm still scoping out what this would look like and would like to make any changes as useful to others as I can so any input would be appreciated.

**Comment by SchrodingersGat** [comment]
@wolffam there is an additional consideration which may make this *very* complex

Let's say you have a "build" which (as its output) makes 15 serialized widgets. Each serialized widget is tracked individually in the system. Each of these widgets has installed in them 1 serialized sub-widget (so 15 sub-widgets in total).

So, each serialized sub-widget must be "installed_in" the serialized widget. We cannot simply assign the sub-widgets to the build, as that does not provide tracking of each individual item.

I think a user-interface on the build which forces the user to assign any serialized stock to a particular serialized output is required.

**Comment by wolffam** [comment]
Can you describe the workflow within Inventree to replicate that scenario?  I'm still trying to grok the project as a whole and want to make sure I understand the intended use of builds.

**Comment by LarryJoy** [comment]
I suggest you have a look at ANSI/ASME Y14.44 **Reference Designations for Electrical and Electronics Parts and Equipment**. Use Figure 7 **Typical System Subdivision** with proper reference designator prefix(s) assigned. In the scenario where you have a PCBA plugging into a socket on another PCBA (motherboard), your motherboard parts list (PL)/BOM would have all the parts for the motherboard including the socket with ref des XA1 and the plugged in PCBA (RPi) that would be reference designated A1. If there are variances you take care of this with the part number, which is a suffix number added to the assembly drawing number. As far as tracking serial numbers you would do this with the manufacturing traveler.
--Larry

**Comment by Kedarius** [comment]
@wolffam @SchrodingersGat  The ability to link items would be great at two levels: part and stock. 

The part one would be rather uncomplicated as it would be "just" a named link between two parts. For example: "ATMEGA328pb" is alternative to "ATMEGA328p" or "PAM2319" is successor of "PAM2306". 

The stock one should be able to take into account the serialized parts. Basically the "RPi serial 1234" is in "PCB 567". I do understand that is is similar to a build but as @SchrodingersGat said, it would mean that I would need to build it one by one as I need to keep track of which RPi is in which PCB.

**Comment by wolffam** [comment]
@Kedarius , I have the logic coded up for the latter use case but only when the build has a quantity of 1 (as you point out).  Would it be sufficient to only allow "installed_in"/"belongs_to" functionality when you are only building 1 output at a time?  Otherwise I agree with @SchrodingersGat , there would need to be a user interface built to support "this serialized component goes with that serialized build output" when there are more than one build outputs being generated.

As of now, I am aiming to build out the functionality to add the "belongs_to"/"installed_in" tracking for a single build output (I _think_ this is pretty much done) and then figure out how to best approach "modifying" a completed build output

**Comment by Kedarius** [comment]
@wolffam One more thing to consider is that if you would need to have more things combined into one. For example if you would have a PCB for RPi and/or Arduino. Or more simple example a desktop computer with RAM, CPU, HDD and Graphics Card (optional). You want to be able to build a "combined" part using zero, one or more sub parts and still be able to change any of them without the need to care about the rest....

**Comment by wolffam** [comment]
Sorry if I was unclear.  The solution that I am currently working on can handle N number of components for a single assembly.  Let's use the PC example:
In order to assembly PC #7, you will need RAM #5, HDD #6, and 10 (untracked) screws.  [Obviously we are simplifying here for the purposes of the example].  After those parts are allocated and the build is completed, the stock items of RAM #5, HDD #6, and the 10 screws used will show they "belong_to" PC #7 (by reference of PC #7's stock item ID).  I haven't thought about how the "modifying" will work just yet as that will probably require some UI which is not my forte.

The scenario that I am _not_ currently covering is if you wanted to make two or more PCs (8, 9, etc) at the same time.

**Comment by Kedarius** [comment]
@wolffam No you made it clear, it was me who was unclear :-) The thing I mentioned is that when you make such a build and then you need to change for example the HDD then you do not need to undo the whole build but just be able to replace one of the components. 
And with this comes one more complication that you can have an optional part and/or partial build. For example one person inserts CPU and RAM and the other inserts HDD and optionaly GPU.

**Comment by wolffam** [comment]
Exactly.  Being able to "modify" a build in the way you described is my end goal (See #977 ).  I think for a first cut, allowing the user to modify a completed build would only be available to single output builds (along the same lines as the PR above) and the user can move the completed build into a new state for modifying (either "In Progress" or some new "Being Modified" state).  In that state, the user can uninstall subparts (which then go back into stock but maybe with a new status if they're broken) as well as install new subparts.  We'll see how much progress I can make on that before I need UI help!

**Comment by SchrodingersGat** [comment]
@Kedarius this feature has now been implemented - https://github.com/inventree/InvenTree/pull/1019

We are working to make the "install stock item" process work automatically with the "Build Order" functionality. For now, you can install (and uninstall) stock items manually from the StockItem view
