### ISSUE TITLE
Variant Part Parameters: should they be copied over from Template part?

### ISSUE THREAD

**Issue by eeintech** [inventree/InvenTree#955]
This is first a question before being an issue. I realized parameters were not copied over from the Template part, shouldn't they be?
My preference would be that they are copied at the creation of the part variant, but their presence and value post-creation are not tracked with reference to the Template part. That way one can setup the Template part with placeholder parameters and they can easily be edited in the variants of that part.

@SchrodingersGat What do you think?
If you are on-board, happy to take a look on the implementation side.

EDIT: reformulation to match InvenTree's language

**Comment by eeintech** [comment]
Umm it seems like Duplicating also leaves Parameters out of the copied part... Is that intentional too?

**Comment by SchrodingersGat** [comment]
Now that you mention this, it seems exceedingly obvious as a good feature! It's current lack is not intentional.

> If you are on-board, happy to take a look on the implementation side.

This would be great!

**Comment by rco3** [comment]
Is the idea with Template parts and Variants to have, e.g., a Template that represents Metal Film resistors and then Variants are the various specific values, etc, each of which has its own multiple potential Supplier Parts?  Or is a Template intended to act as a sort of Meta-Part that has various manufacturers / suppliers, with each Variant representing (e.g.) an On Semi or a Central Semi version of a particular BJT type?

**Comment by eeintech** [comment]
@rco3 My personal take on this:
- a Template part holds information that can be re-used across "variants" of that part, this is useful in creating a base variant for an assembly that can be derived from, with BoM changes for instance. Variants parts will reference the Template part therefore explicitly creating and showing relationship.
- Template parts shouldn't be used as categories, at least not in InvenTree where categories are separate.
- Component manufacturer alternates should be specified in the Supplier tab, each alternate should have their own entry there. I would create a new Supplier entry **only if** the new manufacturer component's specifications are **exactly** the same as the present ones. If not, I would create a new independent part, not a variant. I could see this being setup as Template part to Variants structure when specifications differ but I don't see a use case. As long as components are well categorized and have clear search keywords, it does not really matter if a component is a variant of another, specifications would prevail.

**Comment by SchrodingersGat** [comment]
@eeintech @rco3 here's how I use variants at my company:

Variants are (for my purposes) "manufacturing variants" where the variant dictates a particular configuration which a customer can order a part. A variant might determine the particular options that come with a part, like harnesses, enclosure, color, specs, etc.

The advantage of using a template / variant system here, rather than just making wholly separate parts in the database, is that these parts are linked in a way that lets you do some special things:

### Serial Numbers

Parts that are linked in a template / variant relationship must have unique serial numbers. e.g. if you have a template part `Widget`, and two variants `Widget-01` and `Widget-02` then any assigned serial numbers must be unique across all these variants.

### Stock Reporting

The "stock" for a template part includes stock for all variants under that part

### Logical Grouping

The template / variant relationship is subtly different to the category / part relationship

**Comment by rco3** [comment]
@SchrodingersGat , @eeintech : thank you both very much.  This makes it all very clear how the template/variant logic works, and the expected use case (which I find quite useful).
